// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	interestTagFieldNames          = builder.RawFieldNames(&InterestTag{})
	interestTagRows                = strings.Join(interestTagFieldNames, ",")
	interestTagRowsExpectAutoSet   = strings.Join(stringx.Remove(interestTagFieldNames, "`tag_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	interestTagRowsWithPlaceHolder = strings.Join(stringx.Remove(interestTagFieldNames, "`tag_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheInterestTagTagIdPrefix   = "cache:interestTag:tagId:"
	cacheInterestTagTagNamePrefix = "cache:interestTag:tagName:"
)

type (
	interestTagModel interface {
		Insert(ctx context.Context, data *InterestTag) (sql.Result, error)
		FindOne(ctx context.Context, tagId uint64) (*InterestTag, error)
		FindOneByTagName(ctx context.Context, tagName string) (*InterestTag, error)
		Update(ctx context.Context, data *InterestTag) error
		Delete(ctx context.Context, tagId uint64) error
	}

	defaultInterestTagModel struct {
		sqlc.CachedConn
		table string
	}

	InterestTag struct {
		TagId      uint64    `db:"tag_id"`      // 标签主键ID，自增
		TagName    string    `db:"tag_name"`    // 标签名称（如：运动、音乐、阅读）
		Color      string    `db:"color"`       // 标签颜色值（如十六进制#FFFFFF、RGB值等）
		Icon       string    `db:"icon"`        // 标签图标线上URL地址
		UsageCount uint64    `db:"usage_count"` // 标签被用户使用的总次数
		Status     uint64    `db:"status"`      // 标签状态：0-禁用，1-正常
		TagDesc    string    `db:"tag_desc"`    // 标签描述（可选，如：运动包含跑步、篮球等）
		CreateTime time.Time `db:"create_time"` // 标签创建时间
		UpdateTime time.Time `db:"update_time"` // 标签更新时间
	}
)

func newInterestTagModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultInterestTagModel {
	return &defaultInterestTagModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`interest_tag`",
	}
}

func (m *defaultInterestTagModel) Delete(ctx context.Context, tagId uint64) error {
	data, err := m.FindOne(ctx, tagId)
	if err != nil {
		return err
	}

	interestTagTagIdKey := fmt.Sprintf("%s%v", cacheInterestTagTagIdPrefix, tagId)
	interestTagTagNameKey := fmt.Sprintf("%s%v", cacheInterestTagTagNamePrefix, data.TagName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `tag_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, tagId)
	}, interestTagTagIdKey, interestTagTagNameKey)
	return err
}

func (m *defaultInterestTagModel) FindOne(ctx context.Context, tagId uint64) (*InterestTag, error) {
	interestTagTagIdKey := fmt.Sprintf("%s%v", cacheInterestTagTagIdPrefix, tagId)
	var resp InterestTag
	err := m.QueryRowCtx(ctx, &resp, interestTagTagIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `tag_id` = ? limit 1", interestTagRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, tagId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInterestTagModel) FindOneByTagName(ctx context.Context, tagName string) (*InterestTag, error) {
	interestTagTagNameKey := fmt.Sprintf("%s%v", cacheInterestTagTagNamePrefix, tagName)
	var resp InterestTag
	err := m.QueryRowIndexCtx(ctx, &resp, interestTagTagNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `tag_name` = ? limit 1", interestTagRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, tagName); err != nil {
			return nil, err
		}
		return resp.TagId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInterestTagModel) Insert(ctx context.Context, data *InterestTag) (sql.Result, error) {
	interestTagTagIdKey := fmt.Sprintf("%s%v", cacheInterestTagTagIdPrefix, data.TagId)
	interestTagTagNameKey := fmt.Sprintf("%s%v", cacheInterestTagTagNamePrefix, data.TagName)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, interestTagRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TagName, data.Color, data.Icon, data.UsageCount, data.Status, data.TagDesc)
	}, interestTagTagIdKey, interestTagTagNameKey)
	return ret, err
}

func (m *defaultInterestTagModel) Update(ctx context.Context, newData *InterestTag) error {
	data, err := m.FindOne(ctx, newData.TagId)
	if err != nil {
		return err
	}

	interestTagTagIdKey := fmt.Sprintf("%s%v", cacheInterestTagTagIdPrefix, data.TagId)
	interestTagTagNameKey := fmt.Sprintf("%s%v", cacheInterestTagTagNamePrefix, data.TagName)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `tag_id` = ?", m.table, interestTagRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.TagName, newData.Color, newData.Icon, newData.UsageCount, newData.Status, newData.TagDesc, newData.TagId)
	}, interestTagTagIdKey, interestTagTagNameKey)
	return err
}

func (m *defaultInterestTagModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheInterestTagTagIdPrefix, primary)
}

func (m *defaultInterestTagModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `tag_id` = ? limit 1", interestTagRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultInterestTagModel) tableName() string {
	return m.table
}
