// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInterestRelationFieldNames          = builder.RawFieldNames(&UserInterestRelation{})
	userInterestRelationRows                = strings.Join(userInterestRelationFieldNames, ",")
	userInterestRelationRowsExpectAutoSet   = strings.Join(stringx.Remove(userInterestRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userInterestRelationRowsWithPlaceHolder = strings.Join(stringx.Remove(userInterestRelationFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserInterestRelationIdPrefix = "cache:userInterestRelation:id:"
)

type (
	userInterestRelationModel interface {
		Insert(ctx context.Context, data *UserInterestRelation) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*UserInterestRelation, error)
		Update(ctx context.Context, data *UserInterestRelation) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultUserInterestRelationModel struct {
		sqlc.CachedConn
		table string
	}

	UserInterestRelation struct {
		Id         uint64    `db:"id"`
		UserId     uint64    `db:"user_id"`
		TagId      uint64    `db:"tag_id"`
		CreateTime time.Time `db:"create_time"`
	}
)

func newUserInterestRelationModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserInterestRelationModel {
	return &defaultUserInterestRelationModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user_interest_relation`",
	}
}

func (m *defaultUserInterestRelationModel) Delete(ctx context.Context, id uint64) error {
	userInterestRelationIdKey := fmt.Sprintf("%s%v", cacheUserInterestRelationIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userInterestRelationIdKey)
	return err
}

func (m *defaultUserInterestRelationModel) FindOne(ctx context.Context, id uint64) (*UserInterestRelation, error) {
	userInterestRelationIdKey := fmt.Sprintf("%s%v", cacheUserInterestRelationIdPrefix, id)
	var resp UserInterestRelation
	err := m.QueryRowCtx(ctx, &resp, userInterestRelationIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInterestRelationRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserInterestRelationModel) Insert(ctx context.Context, data *UserInterestRelation) (sql.Result, error) {
	userInterestRelationIdKey := fmt.Sprintf("%s%v", cacheUserInterestRelationIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userInterestRelationRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TagId)
	}, userInterestRelationIdKey)
	return ret, err
}

func (m *defaultUserInterestRelationModel) Update(ctx context.Context, data *UserInterestRelation) error {
	userInterestRelationIdKey := fmt.Sprintf("%s%v", cacheUserInterestRelationIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userInterestRelationRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.TagId, data.Id)
	}, userInterestRelationIdKey)
	return err
}

func (m *defaultUserInterestRelationModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserInterestRelationIdPrefix, primary)
}

func (m *defaultUserInterestRelationModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userInterestRelationRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserInterestRelationModel) tableName() string {
	return m.table
}
