// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`user_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserUserIdPrefix  = "cache:user:userId:"
	cacheUserQQemailPrefix = "cache:user:qQemail:"
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, userId uint64) (*User, error)
		FindOneByQQemail(ctx context.Context, qQemail string) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, userId uint64) error
	}

	defaultUserModel struct {
		sqlc.CachedConn
		table string
	}

	User struct {
		UserId       uint64    `db:"user_id"`      // 用户主键ID（与关联表user_id完全统一）
		QQemail      string    `db:"QQemail"`      // QQ邮箱（用户登录/标识用）
		Nickname     string    `db:"nickname"`     // 用户昵称
		AvatarUrl    string    `db:"avatar_url"`   // 用户头像URL地址
		Introduction string    `db:"introduction"` // 用户个人简介
		Status       uint64    `db:"status"`       // 用户状态：0-禁用，1-正常，2-注销
		Password     string    `db:"password"`     // 用户密码（建议存储加密后的值，如BCrypt哈希）
		Gender       uint64    `db:"gender"`       // 性别：0-未知，1-男，2-女
		Age          uint64    `db:"age"`          // 用户年龄（0表示未填写）
		CreateTime   time.Time `db:"create_time"`  // 用户创建时间
		UpdateTime   time.Time `db:"update_time"`  // 用户信息更新时间
	}
)

func newUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUserModel {
	return &defaultUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`user`",
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, userId uint64) error {
	data, err := m.FindOne(ctx, userId)
	if err != nil {
		return err
	}

	userQQemailKey := fmt.Sprintf("%s%v", cacheUserQQemailPrefix, data.QQemail)
	userUserIdKey := fmt.Sprintf("%s%v", cacheUserUserIdPrefix, userId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, userId)
	}, userQQemailKey, userUserIdKey)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, userId uint64) (*User, error) {
	userUserIdKey := fmt.Sprintf("%s%v", cacheUserUserIdPrefix, userId)
	var resp User
	err := m.QueryRowCtx(ctx, &resp, userUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByQQemail(ctx context.Context, qQemail string) (*User, error) {
	userQQemailKey := fmt.Sprintf("%s%v", cacheUserQQemailPrefix, qQemail)
	var resp User
	err := m.QueryRowIndexCtx(ctx, &resp, userQQemailKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `QQemail` = ? limit 1", userRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, qQemail); err != nil {
			return nil, err
		}
		return resp.UserId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	userQQemailKey := fmt.Sprintf("%s%v", cacheUserQQemailPrefix, data.QQemail)
	userUserIdKey := fmt.Sprintf("%s%v", cacheUserUserIdPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.QQemail, data.Nickname, data.AvatarUrl, data.Introduction, data.Status, data.Password, data.Gender, data.Age)
	}, userQQemailKey, userUserIdKey)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	data, err := m.FindOne(ctx, newData.UserId)
	if err != nil {
		return err
	}

	userQQemailKey := fmt.Sprintf("%s%v", cacheUserQQemailPrefix, data.QQemail)
	userUserIdKey := fmt.Sprintf("%s%v", cacheUserUserIdPrefix, data.UserId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, userRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.QQemail, newData.Nickname, newData.AvatarUrl, newData.Introduction, newData.Status, newData.Password, newData.Gender, newData.Age, newData.UserId)
	}, userQQemailKey, userUserIdKey)
	return err
}

func (m *defaultUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserUserIdPrefix, primary)
}

func (m *defaultUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", userRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
