// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package tagbranchservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq    = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp   = pb.ApplyStudentVerifyResp
	CanParticipateReq        = pb.CanParticipateReq
	CanParticipateResp       = pb.CanParticipateResp
	CanPublishReq            = pb.CanPublishReq
	CanPublishResp           = pb.CanPublishResp
	CancelStudentVerifyReq   = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp  = pb.CancelStudentVerifyResp
	ConfirmStudentVerifyReq  = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp = pb.ConfirmStudentVerifyResp
	CreditLogItem            = pb.CreditLogItem
	GetAllTagsReq            = pb.GetAllTagsReq
	GetAllTagsResp           = pb.GetAllTagsResp
	GetCreditInfoReq         = pb.GetCreditInfoReq
	GetCreditInfoResp        = pb.GetCreditInfoResp
	GetCreditLogsReq         = pb.GetCreditLogsReq
	GetCreditLogsResp        = pb.GetCreditLogsResp
	GetGroupUserReq          = pb.GetGroupUserReq
	GetGroupUserResponse     = pb.GetGroupUserResponse
	GetTagsByIdsReq          = pb.GetTagsByIdsReq
	GetTagsByIdsResp         = pb.GetTagsByIdsResp
	GetUserTagsRep           = pb.GetUserTagsRep
	GetUserTagsResponse      = pb.GetUserTagsResponse
	GetVerifyCurrentReq      = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp     = pb.GetVerifyCurrentResp
	GetVerifyInfoReq         = pb.GetVerifyInfoReq
	GetVerifyInfoResp        = pb.GetVerifyInfoResp
	GroupUserInfo            = pb.GroupUserInfo
	InitCreditReq            = pb.InitCreditReq
	InitCreditResp           = pb.InitCreditResp
	InterestTag              = pb.InterestTag
	IsVerifiedReq            = pb.IsVerifiedReq
	IsVerifiedResp           = pb.IsVerifiedResp
	LoginReq                 = pb.LoginReq
	LoginResponse            = pb.LoginResponse
	LoginUserInfo            = pb.LoginUserInfo
	LogoutReq                = pb.LogoutReq
	LogoutResponse           = pb.LogoutResponse
	RefreshReq               = pb.RefreshReq
	RefreshResponse          = pb.RefreshResponse
	RegisterReq              = pb.RegisterReq
	RegisterResponse         = pb.RegisterResponse
	TagInfo                  = pb.TagInfo
	TagUsageCountReq         = pb.TagUsageCountReq
	TagUsageCountResp        = pb.TagUsageCountResp
	UpdateScoreReq           = pb.UpdateScoreReq
	UpdateScoreResp          = pb.UpdateScoreResp
	UpdateVerifyStatusReq    = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp   = pb.UpdateVerifyStatusResp
	UserInfo                 = pb.UserInfo
	VerifyModifiedData       = pb.VerifyModifiedData
	VerifyOcrData            = pb.VerifyOcrData

	TagBranchService interface {
		// IncrTagUsageCount 增加标签使用计数（正向操作）
		IncrTagUsageCount(ctx context.Context, in *TagUsageCountReq, opts ...grpc.CallOption) (*TagUsageCountResp, error)
		// DecrTagUsageCount 减少标签使用计数（补偿操作）
		DecrTagUsageCount(ctx context.Context, in *TagUsageCountReq, opts ...grpc.CallOption) (*TagUsageCountResp, error)
	}

	defaultTagBranchService struct {
		cli zrpc.Client
	}
)

func NewTagBranchService(cli zrpc.Client) TagBranchService {
	return &defaultTagBranchService{
		cli: cli,
	}
}

// IncrTagUsageCount 增加标签使用计数（正向操作）
func (m *defaultTagBranchService) IncrTagUsageCount(ctx context.Context, in *TagUsageCountReq, opts ...grpc.CallOption) (*TagUsageCountResp, error) {
	client := pb.NewTagBranchServiceClient(m.cli.Conn())
	return client.IncrTagUsageCount(ctx, in, opts...)
}

// DecrTagUsageCount 减少标签使用计数（补偿操作）
func (m *defaultTagBranchService) DecrTagUsageCount(ctx context.Context, in *TagUsageCountReq, opts ...grpc.CallOption) (*TagUsageCountResp, error) {
	client := pb.NewTagBranchServiceClient(m.cli.Conn())
	return client.DecrTagUsageCount(ctx, in, opts...)
}
