// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	credit "activity-platform/app/user/api/internal/handler/credit"
	verify "activity-platform/app/user/api/internal/handler/verify"
	"activity-platform/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询信用变更记录
				Method:  http.MethodGet,
				Path:    "/credit/logs",
				Handler: credit.GetCreditLogsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 提交学生认证申请
				Method:  http.MethodPost,
				Path:    "/verify/student/apply",
				Handler: verify.ApplyVerifyHandler(serverCtx),
			},
			{
				// 取消认证申请
				Method:  http.MethodPost,
				Path:    "/verify/student/cancel",
				Handler: verify.CancelVerifyHandler(serverCtx),
			},
			{
				// 用户确认/修改认证信息
				Method:  http.MethodPost,
				Path:    "/verify/student/confirm",
				Handler: verify.ConfirmVerifyHandler(serverCtx),
			},
			{
				// 获取当前认证进度
				Method:  http.MethodGet,
				Path:    "/verify/student/current",
				Handler: verify.GetVerifyCurrentHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1"),
	)
}
