// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: chat.proto

package chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatService_CreateGroup_FullMethodName          = "/chat.ChatService/CreateGroup"
	ChatService_AddGroupMember_FullMethodName       = "/chat.ChatService/AddGroupMember"
	ChatService_RemoveGroupMember_FullMethodName    = "/chat.ChatService/RemoveGroupMember"
	ChatService_DisbandGroup_FullMethodName         = "/chat.ChatService/DisbandGroup"
	ChatService_GetGroupInfo_FullMethodName         = "/chat.ChatService/GetGroupInfo"
	ChatService_GetGroupMembers_FullMethodName      = "/chat.ChatService/GetGroupMembers"
	ChatService_GetUserGroups_FullMethodName        = "/chat.ChatService/GetUserGroups"
	ChatService_GetGroupByActivityId_FullMethodName = "/chat.ChatService/GetGroupByActivityId"
	ChatService_SaveMessage_FullMethodName          = "/chat.ChatService/SaveMessage"
	ChatService_GetMessageHistory_FullMethodName    = "/chat.ChatService/GetMessageHistory"
	ChatService_GetOfflineMessages_FullMethodName   = "/chat.ChatService/GetOfflineMessages"
	ChatService_CreateNotification_FullMethodName   = "/chat.ChatService/CreateNotification"
	ChatService_GetNotifications_FullMethodName     = "/chat.ChatService/GetNotifications"
	ChatService_MarkNotificationRead_FullMethodName = "/chat.ChatService/MarkNotificationRead"
	ChatService_GetUnreadCount_FullMethodName       = "/chat.ChatService/GetUnreadCount"
	ChatService_MarkAllRead_FullMethodName          = "/chat.ChatService/MarkAllRead"
)

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	// CreateGroup 创建群聊
	// 用于活动创建时自动生成群聊
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	// AddGroupMember 添加群成员
	// 用于用户报名活动后自动加入群聊
	AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error)
	// RemoveGroupMember 移除群成员
	// 用于踢出群成员或用户主动退群（用户取消报名）
	RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*RemoveGroupMemberResp, error)
	// DisbandGroup 解散群聊
	// 仅群主可操作，解散后群聊状态变为已解散
	DisbandGroup(ctx context.Context, in *DisbandGroupReq, opts ...grpc.CallOption) (*DisbandGroupResp, error)
	// GetGroupInfo 获取群聊信息
	// 返回群聊的基本信息（名称、成员数、创建时间等）
	GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	// GetGroupMembers 获取群成员列表
	// 支持分页查询，返回群内所有成员信息
	GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
	// GetUserGroups 获取用户群列表
	// 查询用户加入的所有群聊，支持分页
	GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error)
	// GetGroupByActivityId 通过活动ID获取群聊
	// 根据活动ID查询对应的群聊信息
	GetGroupByActivityId(ctx context.Context, in *GetGroupByActivityIdReq, opts ...grpc.CallOption) (*GetGroupByActivityIdResp, error)
	// SaveMessage 保存消息
	// 用于 WebSocket 服务发送消息时持久化到数据库
	SaveMessage(ctx context.Context, in *SaveMessageReq, opts ...grpc.CallOption) (*SaveMessageResp, error)
	// GetMessageHistory 获取历史消息
	// 分页查询指定群聊的历史消息记录
	GetMessageHistory(ctx context.Context, in *GetMessageHistoryReq, opts ...grpc.CallOption) (*GetMessageHistoryResp, error)
	// GetOfflineMessages 获取离线消息
	// 用户上线后拉取离线期间错过的消息
	GetOfflineMessages(ctx context.Context, in *GetOfflineMessagesReq, opts ...grpc.CallOption) (*GetOfflineMessagesResp, error)
	// CreateNotification 创建系统通知
	// 用于生成各类系统通知（注册成功、报名成功、加入群聊等）
	CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error)
	// GetNotifications 获取通知列表
	// 分页查询用户的系统通知，支持按已读/未读筛选
	GetNotifications(ctx context.Context, in *GetNotificationsReq, opts ...grpc.CallOption) (*GetNotificationsResp, error)
	// MarkNotificationRead 标记通知已读
	// 将指定通知标记为已读状态
	MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error)
	// GetUnreadCount 获取未读通知数量
	// 快速查询用户的未读通知数量，用于显示小红点
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
	// MarkAllRead 全部标记已读
	// 一键将用户的所有未读通知标记为已读
	MarkAllRead(ctx context.Context, in *MarkAllReadReq, opts ...grpc.CallOption) (*MarkAllReadResp, error)
}

type chatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatServiceClient(cc grpc.ClientConnInterface) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, ChatService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) AddGroupMember(ctx context.Context, in *AddGroupMemberReq, opts ...grpc.CallOption) (*AddGroupMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGroupMemberResp)
	err := c.cc.Invoke(ctx, ChatService_AddGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) RemoveGroupMember(ctx context.Context, in *RemoveGroupMemberReq, opts ...grpc.CallOption) (*RemoveGroupMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveGroupMemberResp)
	err := c.cc.Invoke(ctx, ChatService_RemoveGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) DisbandGroup(ctx context.Context, in *DisbandGroupReq, opts ...grpc.CallOption) (*DisbandGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisbandGroupResp)
	err := c.cc.Invoke(ctx, ChatService_DisbandGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, ChatService_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersResp)
	err := c.cc.Invoke(ctx, ChatService_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUserGroups(ctx context.Context, in *GetUserGroupsReq, opts ...grpc.CallOption) (*GetUserGroupsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserGroupsResp)
	err := c.cc.Invoke(ctx, ChatService_GetUserGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetGroupByActivityId(ctx context.Context, in *GetGroupByActivityIdReq, opts ...grpc.CallOption) (*GetGroupByActivityIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupByActivityIdResp)
	err := c.cc.Invoke(ctx, ChatService_GetGroupByActivityId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) SaveMessage(ctx context.Context, in *SaveMessageReq, opts ...grpc.CallOption) (*SaveMessageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveMessageResp)
	err := c.cc.Invoke(ctx, ChatService_SaveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetMessageHistory(ctx context.Context, in *GetMessageHistoryReq, opts ...grpc.CallOption) (*GetMessageHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMessageHistoryResp)
	err := c.cc.Invoke(ctx, ChatService_GetMessageHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetOfflineMessages(ctx context.Context, in *GetOfflineMessagesReq, opts ...grpc.CallOption) (*GetOfflineMessagesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOfflineMessagesResp)
	err := c.cc.Invoke(ctx, ChatService_GetOfflineMessages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) CreateNotification(ctx context.Context, in *CreateNotificationReq, opts ...grpc.CallOption) (*CreateNotificationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNotificationResp)
	err := c.cc.Invoke(ctx, ChatService_CreateNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsReq, opts ...grpc.CallOption) (*GetNotificationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNotificationsResp)
	err := c.cc.Invoke(ctx, ChatService_GetNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MarkNotificationRead(ctx context.Context, in *MarkNotificationReadReq, opts ...grpc.CallOption) (*MarkNotificationReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkNotificationReadResp)
	err := c.cc.Invoke(ctx, ChatService_MarkNotificationRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResp)
	err := c.cc.Invoke(ctx, ChatService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadReq, opts ...grpc.CallOption) (*MarkAllReadResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResp)
	err := c.cc.Invoke(ctx, ChatService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility.
type ChatServiceServer interface {
	// CreateGroup 创建群聊
	// 用于活动创建时自动生成群聊
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	// AddGroupMember 添加群成员
	// 用于用户报名活动后自动加入群聊
	AddGroupMember(context.Context, *AddGroupMemberReq) (*AddGroupMemberResp, error)
	// RemoveGroupMember 移除群成员
	// 用于踢出群成员或用户主动退群（用户取消报名）
	RemoveGroupMember(context.Context, *RemoveGroupMemberReq) (*RemoveGroupMemberResp, error)
	// DisbandGroup 解散群聊
	// 仅群主可操作，解散后群聊状态变为已解散
	DisbandGroup(context.Context, *DisbandGroupReq) (*DisbandGroupResp, error)
	// GetGroupInfo 获取群聊信息
	// 返回群聊的基本信息（名称、成员数、创建时间等）
	GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error)
	// GetGroupMembers 获取群成员列表
	// 支持分页查询，返回群内所有成员信息
	GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error)
	// GetUserGroups 获取用户群列表
	// 查询用户加入的所有群聊，支持分页
	GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error)
	// GetGroupByActivityId 通过活动ID获取群聊
	// 根据活动ID查询对应的群聊信息
	GetGroupByActivityId(context.Context, *GetGroupByActivityIdReq) (*GetGroupByActivityIdResp, error)
	// SaveMessage 保存消息
	// 用于 WebSocket 服务发送消息时持久化到数据库
	SaveMessage(context.Context, *SaveMessageReq) (*SaveMessageResp, error)
	// GetMessageHistory 获取历史消息
	// 分页查询指定群聊的历史消息记录
	GetMessageHistory(context.Context, *GetMessageHistoryReq) (*GetMessageHistoryResp, error)
	// GetOfflineMessages 获取离线消息
	// 用户上线后拉取离线期间错过的消息
	GetOfflineMessages(context.Context, *GetOfflineMessagesReq) (*GetOfflineMessagesResp, error)
	// CreateNotification 创建系统通知
	// 用于生成各类系统通知（注册成功、报名成功、加入群聊等）
	CreateNotification(context.Context, *CreateNotificationReq) (*CreateNotificationResp, error)
	// GetNotifications 获取通知列表
	// 分页查询用户的系统通知，支持按已读/未读筛选
	GetNotifications(context.Context, *GetNotificationsReq) (*GetNotificationsResp, error)
	// MarkNotificationRead 标记通知已读
	// 将指定通知标记为已读状态
	MarkNotificationRead(context.Context, *MarkNotificationReadReq) (*MarkNotificationReadResp, error)
	// GetUnreadCount 获取未读通知数量
	// 快速查询用户的未读通知数量，用于显示小红点
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error)
	// MarkAllRead 全部标记已读
	// 一键将用户的所有未读通知标记为已读
	MarkAllRead(context.Context, *MarkAllReadReq) (*MarkAllReadResp, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatServiceServer struct{}

func (UnimplementedChatServiceServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedChatServiceServer) AddGroupMember(context.Context, *AddGroupMemberReq) (*AddGroupMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGroupMember not implemented")
}
func (UnimplementedChatServiceServer) RemoveGroupMember(context.Context, *RemoveGroupMemberReq) (*RemoveGroupMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveGroupMember not implemented")
}
func (UnimplementedChatServiceServer) DisbandGroup(context.Context, *DisbandGroupReq) (*DisbandGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DisbandGroup not implemented")
}
func (UnimplementedChatServiceServer) GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedChatServiceServer) GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedChatServiceServer) GetUserGroups(context.Context, *GetUserGroupsReq) (*GetUserGroupsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserGroups not implemented")
}
func (UnimplementedChatServiceServer) GetGroupByActivityId(context.Context, *GetGroupByActivityIdReq) (*GetGroupByActivityIdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupByActivityId not implemented")
}
func (UnimplementedChatServiceServer) SaveMessage(context.Context, *SaveMessageReq) (*SaveMessageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveMessage not implemented")
}
func (UnimplementedChatServiceServer) GetMessageHistory(context.Context, *GetMessageHistoryReq) (*GetMessageHistoryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMessageHistory not implemented")
}
func (UnimplementedChatServiceServer) GetOfflineMessages(context.Context, *GetOfflineMessagesReq) (*GetOfflineMessagesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOfflineMessages not implemented")
}
func (UnimplementedChatServiceServer) CreateNotification(context.Context, *CreateNotificationReq) (*CreateNotificationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNotification not implemented")
}
func (UnimplementedChatServiceServer) GetNotifications(context.Context, *GetNotificationsReq) (*GetNotificationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedChatServiceServer) MarkNotificationRead(context.Context, *MarkNotificationReadReq) (*MarkNotificationReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNotificationRead not implemented")
}
func (UnimplementedChatServiceServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedChatServiceServer) MarkAllRead(context.Context, *MarkAllReadReq) (*MarkAllReadResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}
func (UnimplementedChatServiceServer) testEmbeddedByValue()                     {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc.ServiceRegistrar, srv ChatServiceServer) {
	// If the following call panics, it indicates UnimplementedChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_AddGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).AddGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_AddGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).AddGroupMember(ctx, req.(*AddGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_RemoveGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).RemoveGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_RemoveGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).RemoveGroupMember(ctx, req.(*RemoveGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_DisbandGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisbandGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).DisbandGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_DisbandGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).DisbandGroup(ctx, req.(*DisbandGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetGroupInfo(ctx, req.(*GetGroupInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetGroupMembers(ctx, req.(*GetGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUserGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserGroupsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUserGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUserGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUserGroups(ctx, req.(*GetUserGroupsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetGroupByActivityId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupByActivityIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetGroupByActivityId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetGroupByActivityId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetGroupByActivityId(ctx, req.(*GetGroupByActivityIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_SaveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveMessageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).SaveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_SaveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).SaveMessage(ctx, req.(*SaveMessageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetMessageHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMessageHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetMessageHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetMessageHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetMessageHistory(ctx, req.(*GetMessageHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetOfflineMessages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfflineMessagesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetOfflineMessages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetOfflineMessages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetOfflineMessages(ctx, req.(*GetOfflineMessagesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_CreateNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNotificationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).CreateNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_CreateNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).CreateNotification(ctx, req.(*CreateNotificationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetNotifications(ctx, req.(*GetNotificationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MarkNotificationRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkNotificationReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MarkNotificationRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MarkNotificationRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MarkNotificationRead(ctx, req.(*MarkNotificationReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).MarkAllRead(ctx, req.(*MarkAllReadReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _ChatService_CreateGroup_Handler,
		},
		{
			MethodName: "AddGroupMember",
			Handler:    _ChatService_AddGroupMember_Handler,
		},
		{
			MethodName: "RemoveGroupMember",
			Handler:    _ChatService_RemoveGroupMember_Handler,
		},
		{
			MethodName: "DisbandGroup",
			Handler:    _ChatService_DisbandGroup_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _ChatService_GetGroupInfo_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _ChatService_GetGroupMembers_Handler,
		},
		{
			MethodName: "GetUserGroups",
			Handler:    _ChatService_GetUserGroups_Handler,
		},
		{
			MethodName: "GetGroupByActivityId",
			Handler:    _ChatService_GetGroupByActivityId_Handler,
		},
		{
			MethodName: "SaveMessage",
			Handler:    _ChatService_SaveMessage_Handler,
		},
		{
			MethodName: "GetMessageHistory",
			Handler:    _ChatService_GetMessageHistory_Handler,
		},
		{
			MethodName: "GetOfflineMessages",
			Handler:    _ChatService_GetOfflineMessages_Handler,
		},
		{
			MethodName: "CreateNotification",
			Handler:    _ChatService_CreateNotification_Handler,
		},
		{
			MethodName: "GetNotifications",
			Handler:    _ChatService_GetNotifications_Handler,
		},
		{
			MethodName: "MarkNotificationRead",
			Handler:    _ChatService_MarkNotificationRead_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _ChatService_GetUnreadCount_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _ChatService_MarkAllRead_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chat.proto",
}
