// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: chat.proto

package server

import (
	"context"

	"activity-platform/app/chat/rpc/chat"
	"activity-platform/app/chat/rpc/internal/logic"
	"activity-platform/app/chat/rpc/internal/svc"
)

type ChatServiceServer struct {
	svcCtx *svc.ServiceContext
	chat.UnimplementedChatServiceServer
}

func NewChatServiceServer(svcCtx *svc.ServiceContext) *ChatServiceServer {
	return &ChatServiceServer{
		svcCtx: svcCtx,
	}
}

// CreateGroup 创建群聊
func (s *ChatServiceServer) CreateGroup(ctx context.Context, in *chat.CreateGroupReq) (*chat.CreateGroupResp, error) {
	l := logic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

// AddGroupMember 添加群成员
func (s *ChatServiceServer) AddGroupMember(ctx context.Context, in *chat.AddGroupMemberReq) (*chat.AddGroupMemberResp, error) {
	l := logic.NewAddGroupMemberLogic(ctx, s.svcCtx)
	return l.AddGroupMember(in)
}

// RemoveGroupMember 移除群成员
func (s *ChatServiceServer) RemoveGroupMember(ctx context.Context, in *chat.RemoveGroupMemberReq) (*chat.RemoveGroupMemberResp, error) {
	l := logic.NewRemoveGroupMemberLogic(ctx, s.svcCtx)
	return l.RemoveGroupMember(in)
}

// DisbandGroup 解散群聊
func (s *ChatServiceServer) DisbandGroup(ctx context.Context, in *chat.DisbandGroupReq) (*chat.DisbandGroupResp, error) {
	l := logic.NewDisbandGroupLogic(ctx, s.svcCtx)
	return l.DisbandGroup(in)
}

// GetGroupInfo 获取群聊信息
func (s *ChatServiceServer) GetGroupInfo(ctx context.Context, in *chat.GetGroupInfoReq) (*chat.GetGroupInfoResp, error) {
	l := logic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

// GetGroupMembers 获取群成员列表
func (s *ChatServiceServer) GetGroupMembers(ctx context.Context, in *chat.GetGroupMembersReq) (*chat.GetGroupMembersResp, error) {
	l := logic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

// GetUserGroups 获取用户群列表
func (s *ChatServiceServer) GetUserGroups(ctx context.Context, in *chat.GetUserGroupsReq) (*chat.GetUserGroupsResp, error) {
	l := logic.NewGetUserGroupsLogic(ctx, s.svcCtx)
	return l.GetUserGroups(in)
}

// GetGroupByActivityId 通过活动ID获取群聊
func (s *ChatServiceServer) GetGroupByActivityId(ctx context.Context, in *chat.GetGroupByActivityIdReq) (*chat.GetGroupByActivityIdResp, error) {
	l := logic.NewGetGroupByActivityIdLogic(ctx, s.svcCtx)
	return l.GetGroupByActivityId(in)
}

// SaveMessage 保存消息
func (s *ChatServiceServer) SaveMessage(ctx context.Context, in *chat.SaveMessageReq) (*chat.SaveMessageResp, error) {
	l := logic.NewSaveMessageLogic(ctx, s.svcCtx)
	return l.SaveMessage(in)
}

// GetMessageHistory 获取历史消息
func (s *ChatServiceServer) GetMessageHistory(ctx context.Context, in *chat.GetMessageHistoryReq) (*chat.GetMessageHistoryResp, error) {
	l := logic.NewGetMessageHistoryLogic(ctx, s.svcCtx)
	return l.GetMessageHistory(in)
}

// GetOfflineMessages 获取离线消息
func (s *ChatServiceServer) GetOfflineMessages(ctx context.Context, in *chat.GetOfflineMessagesReq) (*chat.GetOfflineMessagesResp, error) {
	l := logic.NewGetOfflineMessagesLogic(ctx, s.svcCtx)
	return l.GetOfflineMessages(in)
}

// CreateNotification 创建系统通知
func (s *ChatServiceServer) CreateNotification(ctx context.Context, in *chat.CreateNotificationReq) (*chat.CreateNotificationResp, error) {
	l := logic.NewCreateNotificationLogic(ctx, s.svcCtx)
	return l.CreateNotification(in)
}

// GetNotifications 获取通知列表
func (s *ChatServiceServer) GetNotifications(ctx context.Context, in *chat.GetNotificationsReq) (*chat.GetNotificationsResp, error) {
	l := logic.NewGetNotificationsLogic(ctx, s.svcCtx)
	return l.GetNotifications(in)
}

// MarkNotificationRead 标记通知已读
func (s *ChatServiceServer) MarkNotificationRead(ctx context.Context, in *chat.MarkNotificationReadReq) (*chat.MarkNotificationReadResp, error) {
	l := logic.NewMarkNotificationReadLogic(ctx, s.svcCtx)
	return l.MarkNotificationRead(in)
}

// GetUnreadCount 获取未读通知数量
func (s *ChatServiceServer) GetUnreadCount(ctx context.Context, in *chat.GetUnreadCountReq) (*chat.GetUnreadCountResp, error) {
	l := logic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

// MarkAllRead 全部标记已读
func (s *ChatServiceServer) MarkAllRead(ctx context.Context, in *chat.MarkAllReadReq) (*chat.MarkAllReadResp, error) {
	l := logic.NewMarkAllReadLogic(ctx, s.svcCtx)
	return l.MarkAllRead(in)
}
