// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/tagbranchservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type TagBranchServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTagBranchServiceServer
}

func NewTagBranchServiceServer(svcCtx *svc.ServiceContext) *TagBranchServiceServer {
	return &TagBranchServiceServer{
		svcCtx: svcCtx,
	}
}

// IncrTagUsageCount 增加标签使用计数（正向操作）
func (s *TagBranchServiceServer) IncrTagUsageCount(ctx context.Context, in *pb.TagUsageCountReq) (*pb.TagUsageCountResp, error) {
	l := tagbranchservicelogic.NewIncrTagUsageCountLogic(ctx, s.svcCtx)
	return l.IncrTagUsageCount(in)
}

// DecrTagUsageCount 减少标签使用计数（补偿操作）
func (s *TagBranchServiceServer) DecrTagUsageCount(ctx context.Context, in *pb.TagUsageCountReq) (*pb.TagUsageCountResp, error) {
	l := tagbranchservicelogic.NewDecrTagUsageCountLogic(ctx, s.svcCtx)
	return l.DecrTagUsageCount(in)
}
