// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ActivityDetail struct {
	Id                   int64   `json:"id"`
	Title                string  `json:"title"`
	CoverUrl             string  `json:"coverUrl"`
	CoverType            int32   `json:"coverType"` // 1=图片, 2=视频
	Content              string  `json:"content"`   // 富文本
	CategoryId           int64   `json:"categoryId"`
	CategoryName         string  `json:"categoryName"`
	OrganizerId          int64   `json:"organizerId"`
	OrganizerName        string  `json:"organizerName"`
	OrganizerAvatar      string  `json:"organizerAvatar"`
	ContactPhone         string  `json:"contactPhone,omitempty"` // 脱敏
	RegisterStartTime    int64   `json:"registerStartTime"`      // 时间戳秒
	RegisterEndTime      int64   `json:"registerEndTime"`
	ActivityStartTime    int64   `json:"activityStartTime"`
	ActivityEndTime      int64   `json:"activityEndTime"`
	Location             string  `json:"location"`
	AddressDetail        string  `json:"addressDetail,omitempty"`
	Longitude            float64 `json:"longitude,omitempty"`
	Latitude             float64 `json:"latitude,omitempty"`
	MaxParticipants      int32   `json:"maxParticipants"` // 0=不限
	CurrentParticipants  int32   `json:"currentParticipants"`
	RequireApproval      bool    `json:"requireApproval"`
	RequireStudentVerify bool    `json:"requireStudentVerify"`
	MinCreditScore       int32   `json:"minCreditScore"`
	Status               int32   `json:"status"` // 0-6
	StatusText           string  `json:"statusText"`
	RejectReason         string  `json:"rejectReason,omitempty"`
	ViewCount            int64   `json:"viewCount"`
	LikeCount            int64   `json:"likeCount"`
	Tags                 []Tag   `json:"tags"`
	CreatedAt            int64   `json:"createdAt"`
	UpdatedAt            int64   `json:"updatedAt"`
	Version              int32   `json:"version"` // 乐观锁版本号
}

type ActivityListItem struct {
	Id                  int64  `json:"id"`
	Title               string `json:"title"`
	CoverUrl            string `json:"coverUrl"`
	CoverType           int32  `json:"coverType"`
	CategoryName        string `json:"categoryName"`
	OrganizerName       string `json:"organizerName"`
	OrganizerAvatar     string `json:"organizerAvatar"`
	ActivityStartTime   int64  `json:"activityStartTime"`
	Location            string `json:"location"`
	MaxParticipants     int32  `json:"maxParticipants"`
	CurrentParticipants int32  `json:"currentParticipants"`
	Status              int32  `json:"status"`
	StatusText          string `json:"statusText"`
	Tags                []Tag  `json:"tags"`
	ViewCount           int64  `json:"viewCount"`
	CreatedAt           int64  `json:"createdAt"`
}

type ActivityListItems struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Time     string `json:"time"`
	Status   string `json:"status"`
	ImageUrl string `json:"imageUrl"`
}

type ApproveActivityReq struct {
	Id int64 `path:"id"`
}

type ApproveActivityResp struct {
	Status int32 `json:"status"` // 2=已发布
}

type CancelActivityReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason,optional"`
}

type CancelActivityRequest struct {
	ActivityId int64 `json:"activityId"`
}

type CancelActivityResp struct {
	Status int32 `json:"status"` // 6=已取消
}

type CancelActivityResponse struct {
	Result string `json:"result"`
}

type Category struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
	Icon string `json:"icon,omitempty"`
	Sort int32  `json:"sort"`
}

type CreateActivityReq struct {
	Title                string  `json:"title"`               // 必填，2-100字
	CoverImageId         int64   `json:"coverImageId"`        // 必填，封面图片ID
	CoverType            int32   `json:"coverType,default=1"` // 1=图片(默认), 2=视频
	Content              string  `json:"content,optional"`    // 富文本
	CategoryId           int64   `json:"categoryId"`          // 必填
	ContactPhone         string  `json:"contactPhone,optional"`
	RegisterStartTime    int64   `json:"registerStartTime"` // 必填
	RegisterEndTime      int64   `json:"registerEndTime"`   // 必填
	ActivityStartTime    int64   `json:"activityStartTime"` // 必填
	ActivityEndTime      int64   `json:"activityEndTime"`   // 必填
	Location             string  `json:"location"`          // 必填
	AddressDetail        string  `json:"addressDetail,optional"`
	Longitude            float64 `json:"longitude,optional"`
	Latitude             float64 `json:"latitude,optional"`
	MaxParticipants      int32   `json:"maxParticipants,default=0"` // 0=不限
	RequireApproval      bool    `json:"requireApproval,default=false"`
	RequireStudentVerify bool    `json:"requireStudentVerify,default=false"`
	MinCreditScore       int32   `json:"minCreditScore,default=0"`
	TagIds               []int64 `json:"tagIds,optional"`       // 最多5个
	IsDraft              bool    `json:"isDraft,default=false"` // true=保存草稿
}

type CreateActivityResp struct {
	Id     int64 `json:"id"`
	Status int32 `json:"status"` // 0=草稿，1=待审核
}

type DeleteActivityReq struct {
	Id int64 `path:"id"`
}

type DeleteActivityResp struct {
	Success bool `json:"success"`
}

type GetActivityListRequest struct {
	Page     int32  `form:"page"`
	PageSize int32  `form:"pageSize"`
	Type     string `form:"type"`
}

type GetActivityListResponse struct {
	Total    int32               `json:"total"`
	Items    []ActivityListItems `json:"items"`
	Page     int32               `json:"page"`
	PageSize int32               `json:"pageSize"`
}

type GetActivityReq struct {
	Id int64 `path:"id"`
}

type GetActivityResp struct {
	Activity ActivityDetail `json:"activity"`
}

type GetHotActivityReq struct {
	Limit int32 `form:"limit,default=10"` // 最大20
}

type GetHotActivityResp struct {
	List []ActivityListItem `json:"list"`
}

type GetTicketDetailRequest struct {
	TicketId int64 `form:"ticketId"`
}

type GetTicketDetailResponse struct {
	TicketId     int64  `json:"ticketId"`
	TicketCode   string `json:"ticketCode"`
	ActivityId   int64  `json:"activityId"`
	ActivityName string `json:"activityName"`
	ActivityTime string `json:"activityTime"`
	QrCodeUrl    string `json:"qrCodeUrl"`
}

type GetTicketListRequest struct {
	Page     int32 `form:"page"`
	PageSize int32 `form:"pageSize"`
}

type GetTicketListResponse struct {
	Total    int32            `json:"total"`
	Items    []TicketListItem `json:"items"`
	Page     int32            `json:"page"`
	PageSize int32            `json:"pageSize"`
}

type IncrViewCountReq struct {
	Id int64 `path:"id"`
}

type IncrViewCountResp struct {
	ViewCount int64 `json:"viewCount"`
}

type ListActivityReq struct {
	Page       int32  `form:"page,default=1"`
	PageSize   int32  `form:"pageSize,default=10"`
	CategoryId int64  `form:"categoryId,optional"`     // 分类筛选
	Status     int32  `form:"status,default=-1"`       // -1=公开状态, -2=全部
	Sort       string `form:"sort,default=created_at"` // created_at, hot, start_time
}

type ListActivityResp struct {
	List       []ActivityListItem `json:"list"`
	Pagination Pagination         `json:"pagination"`
}

type ListCategoryReq struct {
}

type ListCategoryResp struct {
	List []Category `json:"list"`
}

type ListTagReq struct {
	Limit int32 `form:"limit,optional"` // 0=全部，>0=热门N个
}

type ListTagResp struct {
	List []Tag `json:"list"`
}

type MyActivityReq struct {
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"pageSize,default=10"`
}

type MyActivityResp struct {
	List       []ActivityListItem `json:"list"`
	Pagination Pagination         `json:"pagination"`
}

type Pagination struct {
	Page       int32 `json:"page"`
	PageSize   int32 `json:"pageSize"`
	Total      int64 `json:"total"`
	TotalPages int32 `json:"totalPages"`
}

type RegisterActivityRequest struct {
	ActivityId int64 `json:"activityId"`
}

type RegisterActivityResponse struct {
	Result string `json:"result"`
	Reason string `json:"reason"`
}

type RejectActivityReq struct {
	Id     int64  `path:"id"`
	Reason string `json:"reason"` // 必填，1-500字
}

type RejectActivityResp struct {
	Status int32 `json:"status"` // 5=已拒绝
}

type SearchActivityReq struct {
	Keyword    string `form:"keyword"` // 必填，2-50字
	CategoryId int64  `form:"categoryId,optional"`
	Page       int32  `form:"page,default=1"`
	PageSize   int32  `form:"pageSize,default=10"`
	Sort       string `form:"sort,default=relevance"` // relevance, time, hot
}

type SearchActivityResp struct {
	List        []ActivityListItem `json:"list"`
	Total       int64              `json:"total"`
	QueryTimeMs int32              `json:"queryTimeMs"` // 搜索耗时（毫秒）
}

type SubmitActivityReq struct {
	Id int64 `path:"id"`
}

type SubmitActivityResp struct {
	Status int32 `json:"status"` // 1=待审核
}

type Tag struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Color string `json:"color,omitempty"`
	Icon  string `json:"icon,omitempty"`
}

type TicketListItem struct {
	TicketId         int64  `json:"ticketId"`
	ActivityId       int64  `json:"activityId"`
	ActivityName     string `json:"activityName"`
	ActivityTime     string `json:"activityTime"`
	ActivityImageUrl string `json:"activityImageUrl"`
	Status           int32  `json:"status"`
}

type UpdateActivityReq struct {
	Id                   int64    `path:"id"`      // 路径参数
	Version              int32    `json:"version"` // 乐观锁版本号（必填）
	Title                *string  `json:"title,optional"`
	CoverImageId         *int64   `json:"coverImageId,optional"`
	CoverType            *int32   `json:"coverType,optional"`
	Content              *string  `json:"content,optional"`
	CategoryId           *int64   `json:"categoryId,optional"`
	ContactPhone         *string  `json:"contactPhone,optional"`
	RegisterStartTime    *int64   `json:"registerStartTime,optional"`
	RegisterEndTime      *int64   `json:"registerEndTime,optional"`
	ActivityStartTime    *int64   `json:"activityStartTime,optional"`
	ActivityEndTime      *int64   `json:"activityEndTime,optional"`
	Location             *string  `json:"location,optional"`
	AddressDetail        *string  `json:"addressDetail,optional"`
	Longitude            *float64 `json:"longitude,optional"`
	Latitude             *float64 `json:"latitude,optional"`
	MaxParticipants      *int32   `json:"maxParticipants,optional"`
	RequireApproval      *bool    `json:"requireApproval,optional"`
	RequireStudentVerify *bool    `json:"requireStudentVerify,optional"`
	MinCreditScore       *int32   `json:"minCreditScore,optional"`
	TagIds               []int64  `json:"tagIds,optional"`
	UpdateTags           bool     `json:"updateTags,default=false"` // true=更新标签
}

type UpdateActivityResp struct {
	Status     int32 `json:"status"`
	NewVersion int32 `json:"newVersion"`
}

type VerifyTicketRequest struct {
	ActivityId int64  `json:"activityId"`
	TicketCode string `json:"ticketCode"`
	TotpCode   string `json:"totpCode"`
}

type VerifyTicketResponse struct {
	Result string `json:"result"`
}
