// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/tagservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type TagServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedTagServiceServer
}

func NewTagServiceServer(svcCtx *svc.ServiceContext) *TagServiceServer {
	return &TagServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *TagServiceServer) GetAllTags(ctx context.Context, in *pb.GetAllTagsReq) (*pb.GetAllTagsResp, error) {
	l := tagservicelogic.NewGetAllTagsLogic(ctx, s.svcCtx)
	return l.GetAllTags(in)
}

func (s *TagServiceServer) GetTagsByIds(ctx context.Context, in *pb.GetTagsByIdsReq) (*pb.GetTagsByIdsResp, error) {
	l := tagservicelogic.NewGetTagsByIdsLogic(ctx, s.svcCtx)
	return l.GetTagsByIds(in)
}

func (s *TagServiceServer) GetUserTags(ctx context.Context, in *pb.GetUserTagsRep) (*pb.GetUserTagsResponse, error) {
	l := tagservicelogic.NewGetUserTagsLogic(ctx, s.svcCtx)
	return l.GetUserTags(in)
}
