// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	activity "activity-platform/app/activity/api/internal/handler/activity"
	admin "activity-platform/app/activity/api/internal/handler/admin"
	public "activity-platform/app/activity/api/internal/handler/public"
	ticket "activity-platform/app/activity/api/internal/handler/ticket"
	"activity-platform/app/activity/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 创建活动
				Method:  http.MethodPost,
				Path:    "/",
				Handler: activity.CreateActivityHandler(serverCtx),
			},
			{
				// 更新活动
				Method:  http.MethodPut,
				Path:    "/:id",
				Handler: activity.UpdateActivityHandler(serverCtx),
			},
			{
				// 删除活动
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: activity.DeleteActivityHandler(serverCtx),
			},
			{
				// 取消活动
				Method:  http.MethodPost,
				Path:    "/:id/cancel",
				Handler: activity.CancelActivityHandler(serverCtx),
			},
			{
				// 提交审核
				Method:  http.MethodPost,
				Path:    "/:id/submit",
				Handler: activity.SubmitActivityHandler(serverCtx),
			},
			{
				// 我创建的活动
				Method:  http.MethodGet,
				Path:    "/my/created",
				Handler: activity.MyCreatedActivityHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/activity"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminAuth},
			[]rest.Route{
				{
					// 审核通过
					Method:  http.MethodPost,
					Path:    "/:id/approve",
					Handler: admin.ApproveActivityHandler(serverCtx),
				},
				{
					// 审核拒绝
					Method:  http.MethodPost,
					Path:    "/:id/reject",
					Handler: admin.RejectActivityHandler(serverCtx),
				},
				{
					// 管理员活动列表
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: admin.AdminListActivityHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/admin/activity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 活动详情
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: public.GetActivityHandler(serverCtx),
			},
			{
				// 增加浏览量
				Method:  http.MethodPost,
				Path:    "/:id/view",
				Handler: public.IncrViewCountHandler(serverCtx),
			},
			{
				// 分类列表
				Method:  http.MethodGet,
				Path:    "/categories",
				Handler: public.ListCategoryHandler(serverCtx),
			},
			{
				// 热门活动
				Method:  http.MethodGet,
				Path:    "/hot",
				Handler: public.GetHotActivityHandler(serverCtx),
			},
			{
				// 活动列表
				Method:  http.MethodGet,
				Path:    "/lists",
				Handler: public.ListActivityHandler(serverCtx),
			},
			{
				// 搜索活动
				Method:  http.MethodGet,
				Path:    "/search",
				Handler: public.SearchActivityHandler(serverCtx),
			},
			{
				// 标签列表
				Method:  http.MethodGet,
				Path:    "/tags",
				Handler: public.ListTagHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/activity"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 取消报名活动
				Method:  http.MethodPost,
				Path:    "/cancel",
				Handler: ticket.CancelActivitiesHandler(serverCtx),
			},
			{
				// 获取待参加/已参加活动列表
				Method:  http.MethodGet,
				Path:    "/list",
				Handler: ticket.GetActivityListHandler(serverCtx),
			},
			{
				// 报名活动
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: ticket.RegisterActivityHandler(serverCtx),
			},
			{
				// 获取个人票券列表
				Method:  http.MethodGet,
				Path:    "/tickets",
				Handler: ticket.GetTicketListHandler(serverCtx),
			},
			{
				// 获取票券详情
				Method:  http.MethodGet,
				Path:    "/tickets/detail",
				Handler: ticket.GetTicketDetailHandler(serverCtx),
			},
			{
				// 核销票券
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: ticket.VerifyTicketHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/activity"),
	)
}
