// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package tagservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq    = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp   = pb.ApplyStudentVerifyResp
	CanParticipateReq        = pb.CanParticipateReq
	CanParticipateResp       = pb.CanParticipateResp
	CanPublishReq            = pb.CanPublishReq
	CanPublishResp           = pb.CanPublishResp
	CancelStudentVerifyReq   = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp  = pb.CancelStudentVerifyResp
	CaptchaArgs              = pb.CaptchaArgs
	CheckCaptchaReq          = pb.CheckCaptchaReq
	CheckCaptchaResponse     = pb.CheckCaptchaResponse
	CheckQQEmailReq          = pb.CheckQQEmailReq
	CheckQQEmailResponse     = pb.CheckQQEmailResponse
	ConfirmStudentVerifyReq  = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp = pb.ConfirmStudentVerifyResp
	CreditLogItem            = pb.CreditLogItem
	GetAllTagsReq            = pb.GetAllTagsReq
	GetAllTagsResp           = pb.GetAllTagsResp
	GetCaptchaConfigReq      = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse = pb.GetCaptchaConfigResponse
	GetCreditInfoReq         = pb.GetCreditInfoReq
	GetCreditInfoResp        = pb.GetCreditInfoResp
	GetCreditLogsReq         = pb.GetCreditLogsReq
	GetCreditLogsResp        = pb.GetCreditLogsResp
	GetGroupUserReq          = pb.GetGroupUserReq
	GetGroupUserResponse     = pb.GetGroupUserResponse
	GetTagsByIdsReq          = pb.GetTagsByIdsReq
	GetTagsByIdsResp         = pb.GetTagsByIdsResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResponse      = pb.GetUserInfoResponse
	GetUserTagsReq           = pb.GetUserTagsReq
	GetUserTagsResponse      = pb.GetUserTagsResponse
	GetVerifyCurrentReq      = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp     = pb.GetVerifyCurrentResp
	GetVerifyInfoReq         = pb.GetVerifyInfoReq
	GetVerifyInfoResp        = pb.GetVerifyInfoResp
	GroupUserInfo            = pb.GroupUserInfo
	InitCreditReq            = pb.InitCreditReq
	InitCreditResp           = pb.InitCreditResp
	InterestTag              = pb.InterestTag
	IsVerifiedReq            = pb.IsVerifiedReq
	IsVerifiedResp           = pb.IsVerifiedResp
	LoginReq                 = pb.LoginReq
	LoginResponse            = pb.LoginResponse
	LoginUserInfo            = pb.LoginUserInfo
	LogoutReq                = pb.LogoutReq
	LogoutResponse           = pb.LogoutResponse
	RefreshReq               = pb.RefreshReq
	RefreshResponse          = pb.RefreshResponse
	RegisterReq              = pb.RegisterReq
	RegisterResponse         = pb.RegisterResponse
	SendQQEmailReq           = pb.SendQQEmailReq
	SendQQEmailResponse      = pb.SendQQEmailResponse
	TagInfo                  = pb.TagInfo
	UpdateScoreReq           = pb.UpdateScoreReq
	UpdateScoreResp          = pb.UpdateScoreResp
	UpdateVerifyStatusReq    = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp   = pb.UpdateVerifyStatusResp
	UserInfo                 = pb.UserInfo
	VerifyModifiedData       = pb.VerifyModifiedData
	VerifyOcrData            = pb.VerifyOcrData

	TagService interface {
		// 马肖阳的标签接口
		GetAllTags(ctx context.Context, in *GetAllTagsReq, opts ...grpc.CallOption) (*GetAllTagsResp, error)
		GetTagsByIds(ctx context.Context, in *GetTagsByIdsReq, opts ...grpc.CallOption) (*GetTagsByIdsResp, error)
		GetUserTags(ctx context.Context, in *GetUserTagsReq, opts ...grpc.CallOption) (*GetUserTagsResponse, error)
	}

	defaultTagService struct {
		cli zrpc.Client
	}
)

func NewTagService(cli zrpc.Client) TagService {
	return &defaultTagService{
		cli: cli,
	}
}

// 马肖阳的标签接口
func (m *defaultTagService) GetAllTags(ctx context.Context, in *GetAllTagsReq, opts ...grpc.CallOption) (*GetAllTagsResp, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetAllTags(ctx, in, opts...)
}

func (m *defaultTagService) GetTagsByIds(ctx context.Context, in *GetTagsByIdsReq, opts ...grpc.CallOption) (*GetTagsByIdsResp, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetTagsByIds(ctx, in, opts...)
}

func (m *defaultTagService) GetUserTags(ctx context.Context, in *GetUserTagsReq, opts ...grpc.CallOption) (*GetUserTagsResponse, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetUserTags(ctx, in, opts...)
}
