// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package tagservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CanParticipateReq      = pb.CanParticipateReq
	CanParticipateResp     = pb.CanParticipateResp
	CanPublishReq          = pb.CanPublishReq
	CanPublishResp         = pb.CanPublishResp
	CreditLogItem          = pb.CreditLogItem
	GetAllTagsReq          = pb.GetAllTagsReq
	GetAllTagsResp         = pb.GetAllTagsResp
	GetCreditInfoReq       = pb.GetCreditInfoReq
	GetCreditInfoResp      = pb.GetCreditInfoResp
	GetCreditLogsReq       = pb.GetCreditLogsReq
	GetCreditLogsResp      = pb.GetCreditLogsResp
	GetGroupUserRep        = pb.GetGroupUserRep
	GetGroupUserResponse   = pb.GetGroupUserResponse
	GetTagsByIdsReq        = pb.GetTagsByIdsReq
	GetTagsByIdsResp       = pb.GetTagsByIdsResp
	GetUserTagsRep         = pb.GetUserTagsRep
	GetUserTagsResponse    = pb.GetUserTagsResponse
	InitCreditReq          = pb.InitCreditReq
	InitCreditResp         = pb.InitCreditResp
	IsVerifiedReq          = pb.IsVerifiedReq
	IsVerifiedResp         = pb.IsVerifiedResp
	TagInfo                = pb.TagInfo
	UpdateScoreReq         = pb.UpdateScoreReq
	UpdateScoreResp        = pb.UpdateScoreResp
	UpdateVerifyStatusReq  = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp = pb.UpdateVerifyStatusResp
	UserInfo               = pb.UserInfo
	VerifyOcrData          = pb.VerifyOcrData

	TagService interface {
		GetAllTags(ctx context.Context, in *GetAllTagsReq, opts ...grpc.CallOption) (*GetAllTagsResp, error)
		GetTagsByIds(ctx context.Context, in *GetTagsByIdsReq, opts ...grpc.CallOption) (*GetTagsByIdsResp, error)
		GetUserTags(ctx context.Context, in *GetUserTagsRep, opts ...grpc.CallOption) (*GetUserTagsResponse, error)
	}

	defaultTagService struct {
		cli zrpc.Client
	}
)

func NewTagService(cli zrpc.Client) TagService {
	return &defaultTagService{
		cli: cli,
	}
}

func (m *defaultTagService) GetAllTags(ctx context.Context, in *GetAllTagsReq, opts ...grpc.CallOption) (*GetAllTagsResp, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetAllTags(ctx, in, opts...)
}

func (m *defaultTagService) GetTagsByIds(ctx context.Context, in *GetTagsByIdsReq, opts ...grpc.CallOption) (*GetTagsByIdsResp, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetTagsByIds(ctx, in, opts...)
}

func (m *defaultTagService) GetUserTags(ctx context.Context, in *GetUserTagsRep, opts ...grpc.CallOption) (*GetUserTagsResponse, error) {
	client := pb.NewTagServiceClient(m.cli.Conn())
	return client.GetUserTags(ctx, in, opts...)
}
