// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/verifyservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type VerifyServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVerifyServiceServer
}

func NewVerifyServiceServer(svcCtx *svc.ServiceContext) *VerifyServiceServer {
	return &VerifyServiceServer{
		svcCtx: svcCtx,
	}
}

// IsVerified 查询用户是否已完成学生认证
func (s *VerifyServiceServer) IsVerified(ctx context.Context, in *pb.IsVerifiedReq) (*pb.IsVerifiedResp, error) {
	l := verifyservicelogic.NewIsVerifiedLogic(ctx, s.svcCtx)
	return l.IsVerified(in)
}

// UpdateVerifyStatus 更新认证状态
func (s *VerifyServiceServer) UpdateVerifyStatus(ctx context.Context, in *pb.UpdateVerifyStatusReq) (*pb.UpdateVerifyStatusResp, error) {
	l := verifyservicelogic.NewUpdateVerifyStatusLogic(ctx, s.svcCtx)
	return l.UpdateVerifyStatus(in)
}
