// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/uploadtoqiniu"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type UploadToQiNiuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUploadToQiNiuServer
}

func NewUploadToQiNiuServer(svcCtx *svc.ServiceContext) *UploadToQiNiuServer {
	return &UploadToQiNiuServer{
		svcCtx: svcCtx,
	}
}

func (s *UploadToQiNiuServer) UploadFile(ctx context.Context, in *pb.UploadFileReq) (*pb.UploadFileResponse, error) {
	l := uploadtoqiniulogic.NewUploadFileLogic(ctx, s.svcCtx)
	return l.UploadFile(in)
}

func (s *UploadToQiNiuServer) DeleteFile(ctx context.Context, in *pb.DeleteFileReq) (*pb.DeleteFileResponse, error) {
	l := uploadtoqiniulogic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}
