// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/uploadtoqiniu"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type UploadToQiNiuServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUploadToQiNiuServer
}

func NewUploadToQiNiuServer(svcCtx *svc.ServiceContext) *UploadToQiNiuServer {
	return &UploadToQiNiuServer{
		svcCtx: svcCtx,
	}
}

// 直接上传用户头像（删除旧图并更新DB）
func (s *UploadToQiNiuServer) UploadAvatar(ctx context.Context, in *pb.UploadAvatarReq) (*pb.UploadAvatarResp, error) {
	l := uploadtoqiniulogic.NewUploadAvatarLogic(ctx, s.svcCtx)
	return l.UploadAvatar(in)
}

// 上传学生认证图片（同时处理旧图删除和DB更新）
func (s *UploadToQiNiuServer) UploadStudentCardImages(ctx context.Context, in *pb.UploadStudentCardImagesReq) (*pb.UploadStudentCardImagesResp, error) {
	l := uploadtoqiniulogic.NewUploadStudentCardImagesLogic(ctx, s.svcCtx)
	return l.UploadStudentCardImages(in)
}

// 上传活动封面
func (s *UploadToQiNiuServer) UploadActivityCover(ctx context.Context, in *pb.UploadActivityCoverReq) (*pb.UploadActivityCoverResp, error) {
	l := uploadtoqiniulogic.NewUploadActivityCoverLogic(ctx, s.svcCtx)
	return l.UploadActivityCover(in)
}
