// ============================================================================
// User 模块 Proto 定义文件
// ============================================================================
//
// 文件说明：
//   定义 User 模块的内部 gRPC 服务接口，供【其他微服务】调用。
//   不对外暴露，不经过 Gateway。
//
// 包含服务：
//   - CreditService: 信用分服务
//   - VerifyService: 学生认证服务
//
// 调用方：
//   - Activity RPC（报名/发布权限校验）
//   - MQ Consumer（信用分变更）
//   - User API（查询信用信息）
//
// 字段编号规划：
//   - 1-30: 基础字段
//   - 31-50: 扩展字段
//   警告：字段编号一旦发布使用后不可更改或复用！
//
// 生成命令：
//   cd app/user/rpc
//   goctl rpc protoc user.proto --go_out=./pb --go-grpc_out=./pb --zrpc_out=. -style go_zero
//
// ============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetCreditInfoReq 获取信用信息请求
type GetCreditInfoReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditInfoReq) Reset() {
	*x = GetCreditInfoReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditInfoReq) ProtoMessage() {}

func (x *GetCreditInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditInfoReq.ProtoReflect.Descriptor instead.
func (*GetCreditInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetCreditInfoReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetCreditInfoResp 获取信用信息响应
type GetCreditInfoResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 当前信用分（0-100）
	Score int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// 当前信用等级（0-黑名单,1-风险,2-良好,3-优秀,4-社区之星）
	Level int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	// 等级名称
	LevelName string `protobuf:"bytes,4,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`
	// 是否可发布活动
	CanPublish bool `protobuf:"varint,5,opt,name=can_publish,json=canPublish,proto3" json:"can_publish,omitempty"`
	// 是否可报名活动
	CanParticipate bool `protobuf:"varint,6,opt,name=can_participate,json=canParticipate,proto3" json:"can_participate,omitempty"`
	// 创建时间（Unix时间戳秒）
	CreatedAt int64 `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// 更新时间（Unix时间戳秒）
	UpdatedAt     int64 `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCreditInfoResp) Reset() {
	*x = GetCreditInfoResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCreditInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCreditInfoResp) ProtoMessage() {}

func (x *GetCreditInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCreditInfoResp.ProtoReflect.Descriptor instead.
func (*GetCreditInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetCreditInfoResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetCreditInfoResp) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GetCreditInfoResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GetCreditInfoResp) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *GetCreditInfoResp) GetCanPublish() bool {
	if x != nil {
		return x.CanPublish
	}
	return false
}

func (x *GetCreditInfoResp) GetCanParticipate() bool {
	if x != nil {
		return x.CanParticipate
	}
	return false
}

func (x *GetCreditInfoResp) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *GetCreditInfoResp) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// CanParticipateReq 校验报名资格请求
type CanParticipateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanParticipateReq) Reset() {
	*x = CanParticipateReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanParticipateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanParticipateReq) ProtoMessage() {}

func (x *CanParticipateReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanParticipateReq.ProtoReflect.Descriptor instead.
func (*CanParticipateReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CanParticipateReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// CanParticipateResp 校验报名资格响应
type CanParticipateResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否允许报名
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// 不允许时的原因（allowed=true时为空）
	// 示例: "信用分过低(<60)，账户已被限制报名"
	// 示例: "信用分处于风险区间(60-69)，每日仅限报名1次，今日已用完"
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 当前信用分
	Score int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// 当前信用等级
	Level         int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanParticipateResp) Reset() {
	*x = CanParticipateResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanParticipateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanParticipateResp) ProtoMessage() {}

func (x *CanParticipateResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanParticipateResp.ProtoReflect.Descriptor instead.
func (*CanParticipateResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *CanParticipateResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanParticipateResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CanParticipateResp) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CanParticipateResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// CanPublishReq 校验发布资格请求
type CanPublishReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanPublishReq) Reset() {
	*x = CanPublishReq{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanPublishReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanPublishReq) ProtoMessage() {}

func (x *CanPublishReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanPublishReq.ProtoReflect.Descriptor instead.
func (*CanPublishReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CanPublishReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// CanPublishResp 校验发布资格响应
type CanPublishResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否允许发布
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// 不允许时的原因
	// 示例: "信用分不足90，暂时无法发布活动，请先通过参与活动积累信用"
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	// 当前信用分
	Score int64 `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	// 当前信用等级
	Level         int32 `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanPublishResp) Reset() {
	*x = CanPublishResp{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanPublishResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanPublishResp) ProtoMessage() {}

func (x *CanPublishResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanPublishResp.ProtoReflect.Descriptor instead.
func (*CanPublishResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CanPublishResp) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanPublishResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CanPublishResp) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *CanPublishResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// InitCreditReq 初始化信用分请求
type InitCreditReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCreditReq) Reset() {
	*x = InitCreditReq{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCreditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCreditReq) ProtoMessage() {}

func (x *InitCreditReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCreditReq.ProtoReflect.Descriptor instead.
func (*InitCreditReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *InitCreditReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// InitCreditResp 初始化信用分响应
type InitCreditResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 初始化后的分数（100分）
	Score int64 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// 初始化后的等级（4-社区之星）
	Level         int32 `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitCreditResp) Reset() {
	*x = InitCreditResp{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitCreditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCreditResp) ProtoMessage() {}

func (x *InitCreditResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCreditResp.ProtoReflect.Descriptor instead.
func (*InitCreditResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *InitCreditResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitCreditResp) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *InitCreditResp) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// UpdateScoreReq 变更信用分请求
type UpdateScoreReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 变动类型（详见枚举说明）
	// 1-注册初始化, 2-正常履约(+2), 3-提前24h取消(0),
	// 4-临期取消(-5), 5-爽约(-10), 6-圆满举办(+5),
	// 7-删除活动(-10), 99-管理员调整
	ChangeType int32 `protobuf:"varint,2,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"`
	// 业务来源ID（幂等键，格式: "业务类型:业务ID"）
	// 示例: "activity:1001", "checkin:1001:10001"
	SourceId string `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	// 变动原因描述
	// 示例: "活动[周末篮球赛]签到成功"
	Reason string `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	// 管理员调整时的分值（仅change_type=99时有效）
	AdminDelta    int64 `protobuf:"varint,5,opt,name=admin_delta,json=adminDelta,proto3" json:"admin_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreReq) Reset() {
	*x = UpdateScoreReq{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreReq) ProtoMessage() {}

func (x *UpdateScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreReq.ProtoReflect.Descriptor instead.
func (*UpdateScoreReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateScoreReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateScoreReq) GetChangeType() int32 {
	if x != nil {
		return x.ChangeType
	}
	return 0
}

func (x *UpdateScoreReq) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *UpdateScoreReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateScoreReq) GetAdminDelta() int64 {
	if x != nil {
		return x.AdminDelta
	}
	return 0
}

// UpdateScoreResp 变更信用分响应
type UpdateScoreResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 变动前分数
	BeforeScore int64 `protobuf:"varint,2,opt,name=before_score,json=beforeScore,proto3" json:"before_score,omitempty"`
	// 变动后分数
	AfterScore int64 `protobuf:"varint,3,opt,name=after_score,json=afterScore,proto3" json:"after_score,omitempty"`
	// 实际变动值（正数加分，负数扣分）
	Delta int64 `protobuf:"varint,4,opt,name=delta,proto3" json:"delta,omitempty"`
	// 变动后等级
	NewLevel      int32 `protobuf:"varint,5,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateScoreResp) Reset() {
	*x = UpdateScoreResp{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateScoreResp) ProtoMessage() {}

func (x *UpdateScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateScoreResp.ProtoReflect.Descriptor instead.
func (*UpdateScoreResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateScoreResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateScoreResp) GetBeforeScore() int64 {
	if x != nil {
		return x.BeforeScore
	}
	return 0
}

func (x *UpdateScoreResp) GetAfterScore() int64 {
	if x != nil {
		return x.AfterScore
	}
	return 0
}

func (x *UpdateScoreResp) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *UpdateScoreResp) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

// IsVerifiedReq 查询学生认证状态请求
type IsVerifiedReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户ID
	UserId        int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVerifiedReq) Reset() {
	*x = IsVerifiedReq{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVerifiedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVerifiedReq) ProtoMessage() {}

func (x *IsVerifiedReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVerifiedReq.ProtoReflect.Descriptor instead.
func (*IsVerifiedReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *IsVerifiedReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// IsVerifiedResp 查询学生认证状态响应
type IsVerifiedResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否已完成学生认证
	IsVerified bool `protobuf:"varint,1,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	// 学校名称（已认证时返回，未认证为空）
	SchoolName string `protobuf:"bytes,2,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	// 学号-脱敏（已认证时返回，如 "202301****"）
	StudentId string `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// 院系（已认证时返回）
	Department string `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	// 入学年份（已认证时返回，如 "2023"）
	AdmissionYear string `protobuf:"bytes,5,opt,name=admission_year,json=admissionYear,proto3" json:"admission_year,omitempty"`
	// 认证通过时间（Unix时间戳秒，未认证时为0）
	VerifiedAt    int64 `protobuf:"varint,6,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsVerifiedResp) Reset() {
	*x = IsVerifiedResp{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsVerifiedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsVerifiedResp) ProtoMessage() {}

func (x *IsVerifiedResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsVerifiedResp.ProtoReflect.Descriptor instead.
func (*IsVerifiedResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *IsVerifiedResp) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *IsVerifiedResp) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *IsVerifiedResp) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *IsVerifiedResp) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *IsVerifiedResp) GetAdmissionYear() string {
	if x != nil {
		return x.AdmissionYear
	}
	return ""
}

func (x *IsVerifiedResp) GetVerifiedAt() int64 {
	if x != nil {
		return x.VerifiedAt
	}
	return 0
}

// UpdateVerifyStatusReq 更新认证状态请求
type UpdateVerifyStatusReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 认证记录ID
	VerifyId int64 `protobuf:"varint,1,opt,name=verify_id,json=verifyId,proto3" json:"verify_id,omitempty"`
	// 用户ID
	UserId int64 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 新状态
	// 1-OCR审核中, 2-待确认, 3-人工审核中, 4-已通过, 5-已拒绝, 6-已超时, 7-已取消
	NewStatus int32 `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	// OCR识别数据（状态为2-待确认时填充）
	OcrData *VerifyOcrData `protobuf:"bytes,4,opt,name=ocr_data,json=ocrData,proto3" json:"ocr_data,omitempty"`
	// 拒绝原因（状态为5-已拒绝时填充）
	RejectReason string `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	// 操作来源
	// 示例: "ocr_callback", "manual_review", "timeout_job"
	Operator      string `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVerifyStatusReq) Reset() {
	*x = UpdateVerifyStatusReq{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVerifyStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyStatusReq) ProtoMessage() {}

func (x *UpdateVerifyStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateVerifyStatusReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateVerifyStatusReq) GetVerifyId() int64 {
	if x != nil {
		return x.VerifyId
	}
	return 0
}

func (x *UpdateVerifyStatusReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateVerifyStatusReq) GetNewStatus() int32 {
	if x != nil {
		return x.NewStatus
	}
	return 0
}

func (x *UpdateVerifyStatusReq) GetOcrData() *VerifyOcrData {
	if x != nil {
		return x.OcrData
	}
	return nil
}

func (x *UpdateVerifyStatusReq) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *UpdateVerifyStatusReq) GetOperator() string {
	if x != nil {
		return x.Operator
	}
	return ""
}

// VerifyOcrData OCR识别数据
type VerifyOcrData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 真实姓名
	RealName string `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	// 学校名称
	SchoolName string `protobuf:"bytes,2,opt,name=school_name,json=schoolName,proto3" json:"school_name,omitempty"`
	// 学号
	StudentId string `protobuf:"bytes,3,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	// 院系
	Department string `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	// 入学年份
	AdmissionYear string `protobuf:"bytes,5,opt,name=admission_year,json=admissionYear,proto3" json:"admission_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOcrData) Reset() {
	*x = VerifyOcrData{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOcrData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOcrData) ProtoMessage() {}

func (x *VerifyOcrData) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOcrData.ProtoReflect.Descriptor instead.
func (*VerifyOcrData) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyOcrData) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *VerifyOcrData) GetSchoolName() string {
	if x != nil {
		return x.SchoolName
	}
	return ""
}

func (x *VerifyOcrData) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *VerifyOcrData) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *VerifyOcrData) GetAdmissionYear() string {
	if x != nil {
		return x.AdmissionYear
	}
	return ""
}

// UpdateVerifyStatusResp 更新认证状态响应
type UpdateVerifyStatusResp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否成功
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 更新前状态
	BeforeStatus int32 `protobuf:"varint,2,opt,name=before_status,json=beforeStatus,proto3" json:"before_status,omitempty"`
	// 更新后状态
	AfterStatus   int32 `protobuf:"varint,3,opt,name=after_status,json=afterStatus,proto3" json:"after_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVerifyStatusResp) Reset() {
	*x = UpdateVerifyStatusResp{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVerifyStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVerifyStatusResp) ProtoMessage() {}

func (x *UpdateVerifyStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVerifyStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateVerifyStatusResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateVerifyStatusResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVerifyStatusResp) GetBeforeStatus() int32 {
	if x != nil {
		return x.BeforeStatus
	}
	return 0
}

func (x *UpdateVerifyStatusResp) GetAfterStatus() int32 {
	if x != nil {
		return x.AfterStatus
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"+\n" +
	"\x10GetCreditInfoReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xff\x01\n" +
	"\x11GetCreditInfoResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"level_name\x18\x04 \x01(\tR\tlevelName\x12\x1f\n" +
	"\vcan_publish\x18\x05 \x01(\bR\n" +
	"canPublish\x12'\n" +
	"\x0fcan_participate\x18\x06 \x01(\bR\x0ecanParticipate\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\",\n" +
	"\x11CanParticipateReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"r\n" +
	"\x12CanParticipateResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"(\n" +
	"\rCanPublishReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"n\n" +
	"\x0eCanPublishResp\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x03R\x05score\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\"(\n" +
	"\rInitCreditReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"V\n" +
	"\x0eInitCreditResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x03R\x05score\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\"\xa0\x01\n" +
	"\x0eUpdateScoreReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vchange_type\x18\x02 \x01(\x05R\n" +
	"changeType\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1f\n" +
	"\vadmin_delta\x18\x05 \x01(\x03R\n" +
	"adminDelta\"\xa2\x01\n" +
	"\x0fUpdateScoreResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fbefore_score\x18\x02 \x01(\x03R\vbeforeScore\x12\x1f\n" +
	"\vafter_score\x18\x03 \x01(\x03R\n" +
	"afterScore\x12\x14\n" +
	"\x05delta\x18\x04 \x01(\x03R\x05delta\x12\x1b\n" +
	"\tnew_level\x18\x05 \x01(\x05R\bnewLevel\"(\n" +
	"\rIsVerifiedReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\xd9\x01\n" +
	"\x0eIsVerifiedResp\x12\x1f\n" +
	"\vis_verified\x18\x01 \x01(\bR\n" +
	"isVerified\x12\x1f\n" +
	"\vschool_name\x18\x02 \x01(\tR\n" +
	"schoolName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12%\n" +
	"\x0eadmission_year\x18\x05 \x01(\tR\radmissionYear\x12\x1f\n" +
	"\vverified_at\x18\x06 \x01(\x03R\n" +
	"verifiedAt\"\xdd\x01\n" +
	"\x15UpdateVerifyStatusReq\x12\x1b\n" +
	"\tverify_id\x18\x01 \x01(\x03R\bverifyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"new_status\x18\x03 \x01(\x05R\tnewStatus\x12.\n" +
	"\bocr_data\x18\x04 \x01(\v2\x13.user.VerifyOcrDataR\aocrData\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\x12\x1a\n" +
	"\boperator\x18\x06 \x01(\tR\boperator\"\xb3\x01\n" +
	"\rVerifyOcrData\x12\x1b\n" +
	"\treal_name\x18\x01 \x01(\tR\brealName\x12\x1f\n" +
	"\vschool_name\x18\x02 \x01(\tR\n" +
	"schoolName\x12\x1d\n" +
	"\n" +
	"student_id\x18\x03 \x01(\tR\tstudentId\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12%\n" +
	"\x0eadmission_year\x18\x05 \x01(\tR\radmissionYear\"z\n" +
	"\x16UpdateVerifyStatusResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rbefore_status\x18\x02 \x01(\x05R\fbeforeStatus\x12!\n" +
	"\fafter_status\x18\x03 \x01(\x05R\vafterStatus2\xc4\x02\n" +
	"\rCreditService\x12@\n" +
	"\rGetCreditInfo\x12\x16.user.GetCreditInfoReq\x1a\x17.user.GetCreditInfoResp\x12C\n" +
	"\x0eCanParticipate\x12\x17.user.CanParticipateReq\x1a\x18.user.CanParticipateResp\x127\n" +
	"\n" +
	"CanPublish\x12\x13.user.CanPublishReq\x1a\x14.user.CanPublishResp\x127\n" +
	"\n" +
	"InitCredit\x12\x13.user.InitCreditReq\x1a\x14.user.InitCreditResp\x12:\n" +
	"\vUpdateScore\x12\x14.user.UpdateScoreReq\x1a\x15.user.UpdateScoreResp2\x99\x01\n" +
	"\rVerifyService\x127\n" +
	"\n" +
	"IsVerified\x12\x13.user.IsVerifiedReq\x1a\x14.user.IsVerifiedResp\x12O\n" +
	"\x12UpdateVerifyStatus\x12\x1b.user.UpdateVerifyStatusReq\x1a\x1c.user.UpdateVerifyStatusRespB\x06Z\x04./pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_user_proto_goTypes = []any{
	(*GetCreditInfoReq)(nil),       // 0: user.GetCreditInfoReq
	(*GetCreditInfoResp)(nil),      // 1: user.GetCreditInfoResp
	(*CanParticipateReq)(nil),      // 2: user.CanParticipateReq
	(*CanParticipateResp)(nil),     // 3: user.CanParticipateResp
	(*CanPublishReq)(nil),          // 4: user.CanPublishReq
	(*CanPublishResp)(nil),         // 5: user.CanPublishResp
	(*InitCreditReq)(nil),          // 6: user.InitCreditReq
	(*InitCreditResp)(nil),         // 7: user.InitCreditResp
	(*UpdateScoreReq)(nil),         // 8: user.UpdateScoreReq
	(*UpdateScoreResp)(nil),        // 9: user.UpdateScoreResp
	(*IsVerifiedReq)(nil),          // 10: user.IsVerifiedReq
	(*IsVerifiedResp)(nil),         // 11: user.IsVerifiedResp
	(*UpdateVerifyStatusReq)(nil),  // 12: user.UpdateVerifyStatusReq
	(*VerifyOcrData)(nil),          // 13: user.VerifyOcrData
	(*UpdateVerifyStatusResp)(nil), // 14: user.UpdateVerifyStatusResp
}
var file_user_proto_depIdxs = []int32{
	13, // 0: user.UpdateVerifyStatusReq.ocr_data:type_name -> user.VerifyOcrData
	0,  // 1: user.CreditService.GetCreditInfo:input_type -> user.GetCreditInfoReq
	2,  // 2: user.CreditService.CanParticipate:input_type -> user.CanParticipateReq
	4,  // 3: user.CreditService.CanPublish:input_type -> user.CanPublishReq
	6,  // 4: user.CreditService.InitCredit:input_type -> user.InitCreditReq
	8,  // 5: user.CreditService.UpdateScore:input_type -> user.UpdateScoreReq
	10, // 6: user.VerifyService.IsVerified:input_type -> user.IsVerifiedReq
	12, // 7: user.VerifyService.UpdateVerifyStatus:input_type -> user.UpdateVerifyStatusReq
	1,  // 8: user.CreditService.GetCreditInfo:output_type -> user.GetCreditInfoResp
	3,  // 9: user.CreditService.CanParticipate:output_type -> user.CanParticipateResp
	5,  // 10: user.CreditService.CanPublish:output_type -> user.CanPublishResp
	7,  // 11: user.CreditService.InitCredit:output_type -> user.InitCreditResp
	9,  // 12: user.CreditService.UpdateScore:output_type -> user.UpdateScoreResp
	11, // 13: user.VerifyService.IsVerified:output_type -> user.IsVerifiedResp
	14, // 14: user.VerifyService.UpdateVerifyStatus:output_type -> user.UpdateVerifyStatusResp
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
