// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GetGroupInfoReq struct {
	GroupId string `path:"group_id"`
}

type GetGroupInfoResp struct {
	Code    int32     `json:"code"`
	Message string    `json:"message"`
	Data    GroupInfo `json:"data"`
}

type GetGroupMembersData struct {
	Members  []GroupMemberInfo `json:"members"`
	Total    int32             `json:"total"`
	Page     int32             `json:"page"`
	PageSize int32             `json:"page_size"`
}

type GetGroupMembersReq struct {
	GroupId  string `path:"group_id"`
	Page     int32  `form:"page,default=1"`
	PageSize int32  `form:"page_size,default=20"`
}

type GetGroupMembersResp struct {
	Code    int32               `json:"code"`
	Message string              `json:"message"`
	Data    GetGroupMembersData `json:"data"`
}

type GetMessageHistoryData struct {
	Messages []MessageInfo `json:"messages"`
	HasMore  bool          `json:"has_more"`
}

type GetMessageHistoryReq struct {
	GroupId  string `form:"group_id"`
	BeforeId string `form:"before_id,optional"`
	Limit    int32  `form:"limit,default=20"`
}

type GetMessageHistoryResp struct {
	Code    int32                 `json:"code"`
	Message string                `json:"message"`
	Data    GetMessageHistoryData `json:"data"`
}

type GetNotificationsData struct {
	Total         int32              `json:"total"`
	UnreadCount   int32              `json:"unread_count"`
	Notifications []NotificationInfo `json:"notifications"`
	Page          int32              `json:"page"`
	PageSize      int32              `json:"page_size"`
}

type GetNotificationsReq struct {
	UserId   int64 `form:"user_id"`
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetNotificationsResp struct {
	Code    int32                `json:"code"`
	Message string               `json:"message"`
	Data    GetNotificationsData `json:"data"`
}

type GetOfflineMessagesData struct {
	Messages []MessageInfo `json:"messages"`
}

type GetOfflineMessagesReq struct {
	UserId    int64 `form:"user_id"`
	AfterTime int64 `form:"after_time"`
}

type GetOfflineMessagesResp struct {
	Code    int32                  `json:"code"`
	Message string                 `json:"message"`
	Data    GetOfflineMessagesData `json:"data"`
}

type GetUnreadCountData struct {
	Count int32 `json:"count"`
}

type GetUnreadCountReq struct {
	UserId int64 `form:"user_id"`
}

type GetUnreadCountResp struct {
	Code    int32              `json:"code"`
	Message string             `json:"message"`
	Data    GetUnreadCountData `json:"data"`
}

type GetUserGroupsData struct {
	Groups   []UserGroupInfo `json:"groups"`
	Total    int32           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetUserGroupsReq struct {
	UserId   int64 `path:"user_id"`
	Page     int32 `form:"page,default=1"`
	PageSize int32 `form:"page_size,default=20"`
}

type GetUserGroupsResp struct {
	Code    int32             `json:"code"`
	Message string            `json:"message"`
	Data    GetUserGroupsData `json:"data"`
}

type GetUserStatusData struct {
	IsOnline      bool  `json:"is_online"`
	LastSeen      int64 `json:"last_seen"`
	LastOnlineAt  int64 `json:"last_online_at"`
	LastOfflineAt int64 `json:"last_offline_at"`
}

type GetUserStatusReq struct {
	UserId int64 `form:"user_id"`
}

type GetUserStatusResp struct {
	Code    int32             `json:"code"`
	Message string            `json:"message"`
	Data    GetUserStatusData `json:"data"`
}

type GroupInfo struct {
	GroupId     string `json:"group_id"`
	ActivityId  int64  `json:"activity_id"`
	Name        string `json:"name"`
	OwnerId     int64  `json:"owner_id"`
	MemberCount int32  `json:"member_count"`
	Status      int32  `json:"status"`
	CreatedAt   string `json:"created_at"`
}

type GroupMemberInfo struct {
	UserId   int64  `json:"user_id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
	Role     string `json:"role"` // owner, member
	JoinedAt string `json:"joined_at"`
}

type MarkAllReadData struct {
	UpdatedCount int32 `json:"updated_count"`
}

type MarkAllReadReq struct {
	UserId int64 `json:"user_id"`
}

type MarkAllReadResp struct {
	Code    int32           `json:"code"`
	Message string          `json:"message"`
	Data    MarkAllReadData `json:"data"`
}

type MarkNotificationReadData struct {
	UpdatedCount int32 `json:"updated_count"`
}

type MarkNotificationReadReq struct {
	UserId          int64    `json:"user_id"`
	NotificationIds []string `json:"notification_ids"`
}

type MarkNotificationReadResp struct {
	Code    int32                    `json:"code"`
	Message string                   `json:"message"`
	Data    MarkNotificationReadData `json:"data"`
}

type MessageInfo struct {
	MessageId  string `json:"message_id"`
	GroupId    string `json:"group_id"`
	SenderId   int64  `json:"sender_id"`
	SenderName string `json:"sender_name"`
	MsgType    int32  `json:"msg_type"` // 1-文本 2-图片
	Content    string `json:"content"`
	CreatedAt  string `json:"created_at"`
}

type NotificationInfo struct {
	NotificationId string `json:"notification_id"`
	Type           string `json:"type"`
	Title          string `json:"title"`
	Content        string `json:"content"`
	IsRead         bool   `json:"is_read"`
	CreatedAt      string `json:"created_at"`
}

type UserGroupInfo struct {
	GroupId       string `json:"group_id"`
	ActivityId    int64  `json:"activity_id"`
	Name          string `json:"name"`
	OwnerId       int64  `json:"owner_id"`
	MemberCount   int32  `json:"member_count"`
	Status        int32  `json:"status"`
	Role          string `json:"role"`
	JoinedAt      string `json:"joined_at"`
	LastMessage   string `json:"last_message,optional"`
	LastMessageAt string `json:"last_message_at,optional"`
}

type UserStatusInfo struct {
	IsOnline      bool  `json:"is_online"`
	LastSeen      int64 `json:"last_seen"`
	LastOnlineAt  int64 `json:"last_online_at"`
	LastOfflineAt int64 `json:"last_offline_at"`
}
