// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/qqemail"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type QQEmailServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQQEmailServer
}

func NewQQEmailServer(svcCtx *svc.ServiceContext) *QQEmailServer {
	return &QQEmailServer{
		svcCtx: svcCtx,
	}
}

func (s *QQEmailServer) SendQQEmail(ctx context.Context, in *pb.SendQQEmailReq) (*pb.SendQQEmailResponse, error) {
	l := qqemaillogic.NewSendQQEmailLogic(ctx, s.svcCtx)
	return l.SendQQEmail(in)
}

func (s *QQEmailServer) CheckQQEmail(ctx context.Context, in *pb.CheckQQEmailReq) (*pb.CheckQQEmailResponse, error) {
	l := qqemaillogic.NewCheckQQEmailLogic(ctx, s.svcCtx)
	return l.CheckQQEmail(in)
}
