// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package server

import (
	"context"

	"activity-platform/app/activity/rpc/activity"
	"activity-platform/app/activity/rpc/internal/logic/activitybranchservice"
	"activity-platform/app/activity/rpc/internal/svc"
)

type ActivityBranchServiceServer struct {
	svcCtx *svc.ServiceContext
	activity.UnimplementedActivityBranchServiceServer
}

func NewActivityBranchServiceServer(svcCtx *svc.ServiceContext) *ActivityBranchServiceServer {
	return &ActivityBranchServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建活动 - 正向操作
func (s *ActivityBranchServiceServer) CreateActivityAction(ctx context.Context, in *activity.CreateActivityActionReq) (*activity.CreateActivityActionResp, error) {
	l := activitybranchservicelogic.NewCreateActivityActionLogic(ctx, s.svcCtx)
	return l.CreateActivityAction(in)
}

// 创建活动 - 补偿操作（回滚）
func (s *ActivityBranchServiceServer) CreateActivityCompensate(ctx context.Context, in *activity.CreateActivityCompensateReq) (*activity.CreateActivityCompensateResp, error) {
	l := activitybranchservicelogic.NewCreateActivityCompensateLogic(ctx, s.svcCtx)
	return l.CreateActivityCompensate(in)
}

// 删除活动 - 正向操作
func (s *ActivityBranchServiceServer) DeleteActivityAction(ctx context.Context, in *activity.DeleteActivityActionReq) (*activity.DeleteActivityActionResp, error) {
	l := activitybranchservicelogic.NewDeleteActivityActionLogic(ctx, s.svcCtx)
	return l.DeleteActivityAction(in)
}

// 删除活动 - 补偿操作（回滚）
func (s *ActivityBranchServiceServer) DeleteActivityCompensate(ctx context.Context, in *activity.DeleteActivityCompensateReq) (*activity.DeleteActivityCompensateResp, error) {
	l := activitybranchservicelogic.NewDeleteActivityCompensateLogic(ctx, s.svcCtx)
	return l.DeleteActivityCompensate(in)
}
