// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/userbasicservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type UserBasicServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserBasicServiceServer
}

func NewUserBasicServiceServer(svcCtx *svc.ServiceContext) *UserBasicServiceServer {
	return &UserBasicServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *UserBasicServiceServer) GetGroupUser(ctx context.Context, in *pb.GetGroupUserRep) (*pb.GetGroupUserResponse, error) {
	l := userbasicservicelogic.NewGetGroupUserLogic(ctx, s.svcCtx)
	return l.GetGroupUser(in)
}
