// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/userbasicservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type UserBasicServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserBasicServiceServer
}

func NewUserBasicServiceServer(svcCtx *svc.ServiceContext) *UserBasicServiceServer {
	return &UserBasicServiceServer{
		svcCtx: svcCtx,
	}
}

// 批量获取群聊用户的信息
func (s *UserBasicServiceServer) GetGroupUser(ctx context.Context, in *pb.GetGroupUserReq) (*pb.GetGroupUserResponse, error) {
	l := userbasicservicelogic.NewGetGroupUserLogic(ctx, s.svcCtx)
	return l.GetGroupUser(in)
}

// 用户登录
func (s *UserBasicServiceServer) Login(ctx context.Context, in *pb.LoginReq) (*pb.LoginResponse, error) {
	l := userbasicservicelogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

// 用户登出
func (s *UserBasicServiceServer) Logout(ctx context.Context, in *pb.LogoutReq) (*pb.LogoutResponse, error) {
	l := userbasicservicelogic.NewLogoutLogic(ctx, s.svcCtx)
	return l.Logout(in)
}

// 用户注册
func (s *UserBasicServiceServer) Register(ctx context.Context, in *pb.RegisterReq) (*pb.RegisterResponse, error) {
	l := userbasicservicelogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

// 刷新短token
func (s *UserBasicServiceServer) RefreshToken(ctx context.Context, in *pb.RefreshReq) (*pb.RefreshResponse, error) {
	l := userbasicservicelogic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}

// 获取用户的信息
func (s *UserBasicServiceServer) GetUserInfo(ctx context.Context, in *pb.GetUserInfoReq) (*pb.GetUserInfoResponse, error) {
	l := userbasicservicelogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}
