// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	group "activity-platform/app/chat/api/internal/handler/group"
	message "activity-platform/app/chat/api/internal/handler/message"
	notification "activity-platform/app/chat/api/internal/handler/notification"
	user "activity-platform/app/chat/api/internal/handler/user"
	"activity-platform/app/chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 查询群组信息
				Method:  http.MethodGet,
				Path:    "/groups/:group_id",
				Handler: group.GetGroupInfoHandler(serverCtx),
			},
			{
				// 查询群成员列表
				Method:  http.MethodGet,
				Path:    "/groups/:group_id/members",
				Handler: group.GetGroupMembersHandler(serverCtx),
			},
			{
				// 获取用户的群聊列表
				Method:  http.MethodGet,
				Path:    "/users/:user_id/groups",
				Handler: group.GetUserGroupsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询消息历史
				Method:  http.MethodGet,
				Path:    "/messages",
				Handler: message.GetMessageHistoryHandler(serverCtx),
			},
			{
				// 获取离线消息
				Method:  http.MethodGet,
				Path:    "/messages/offline",
				Handler: message.GetOfflineMessagesHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 查询通知列表
				Method:  http.MethodGet,
				Path:    "/notifications",
				Handler: notification.GetNotificationsHandler(serverCtx),
			},
			{
				// 标记已读
				Method:  http.MethodPost,
				Path:    "/notifications/read",
				Handler: notification.MarkNotificationReadHandler(serverCtx),
			},
			{
				// 标记全部已读
				Method:  http.MethodPost,
				Path:    "/notifications/read-all",
				Handler: notification.MarkAllReadHandler(serverCtx),
			},
			{
				// 获取未读数量
				Method:  http.MethodGet,
				Path:    "/notifications/unread-count",
				Handler: notification.GetUnreadCountHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取用户在线状态
				Method:  http.MethodGet,
				Path:    "/users/status",
				Handler: user.GetUserStatusHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api"),
	)
}
