// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package captchaservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq    = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp   = pb.ApplyStudentVerifyResp
	CanParticipateReq        = pb.CanParticipateReq
	CanParticipateResp       = pb.CanParticipateResp
	CanPublishReq            = pb.CanPublishReq
	CanPublishResp           = pb.CanPublishResp
	CancelStudentVerifyReq   = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp  = pb.CancelStudentVerifyResp
	CaptchaArgs              = pb.CaptchaArgs
	CheckCaptchaReq          = pb.CheckCaptchaReq
	CheckCaptchaResponse     = pb.CheckCaptchaResponse
	CheckQQEmailReq          = pb.CheckQQEmailReq
	CheckQQEmailResponse     = pb.CheckQQEmailResponse
	ConfirmStudentVerifyReq  = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp = pb.ConfirmStudentVerifyResp
	CreditLogItem            = pb.CreditLogItem
	GetAllTagsReq            = pb.GetAllTagsReq
	GetAllTagsResp           = pb.GetAllTagsResp
	GetCaptchaConfigReq      = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse = pb.GetCaptchaConfigResponse
	GetCreditInfoReq         = pb.GetCreditInfoReq
	GetCreditInfoResp        = pb.GetCreditInfoResp
	GetCreditLogsReq         = pb.GetCreditLogsReq
	GetCreditLogsResp        = pb.GetCreditLogsResp
	GetGroupUserReq          = pb.GetGroupUserReq
	GetGroupUserResponse     = pb.GetGroupUserResponse
	GetTagsByIdsReq          = pb.GetTagsByIdsReq
	GetTagsByIdsResp         = pb.GetTagsByIdsResp
	GetUserTagsRep           = pb.GetUserTagsRep
	GetUserTagsResponse      = pb.GetUserTagsResponse
	GetVerifyCurrentReq      = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp     = pb.GetVerifyCurrentResp
	GetVerifyInfoReq         = pb.GetVerifyInfoReq
	GetVerifyInfoResp        = pb.GetVerifyInfoResp
	GroupUserInfo            = pb.GroupUserInfo
	InitCreditReq            = pb.InitCreditReq
	InitCreditResp           = pb.InitCreditResp
	InterestTag              = pb.InterestTag
	IsVerifiedReq            = pb.IsVerifiedReq
	IsVerifiedResp           = pb.IsVerifiedResp
	LoginReq                 = pb.LoginReq
	LoginResponse            = pb.LoginResponse
	LoginUserInfo            = pb.LoginUserInfo
	LogoutReq                = pb.LogoutReq
	LogoutResponse           = pb.LogoutResponse
	RefreshReq               = pb.RefreshReq
	RefreshResponse          = pb.RefreshResponse
	RegisterReq              = pb.RegisterReq
	RegisterResponse         = pb.RegisterResponse
	SendQQEmailReq           = pb.SendQQEmailReq
	SendQQEmailResponse      = pb.SendQQEmailResponse
	TagInfo                  = pb.TagInfo
	UpdateScoreReq           = pb.UpdateScoreReq
	UpdateScoreResp          = pb.UpdateScoreResp
	UpdateVerifyStatusReq    = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp   = pb.UpdateVerifyStatusResp
	UserInfo                 = pb.UserInfo
	VerifyModifiedData       = pb.VerifyModifiedData
	VerifyOcrData            = pb.VerifyOcrData

	CaptchaService interface {
		GetCaptchaConfig(ctx context.Context, in *GetCaptchaConfigReq, opts ...grpc.CallOption) (*GetCaptchaConfigResponse, error)
		CheckCaptcha(ctx context.Context, in *CheckCaptchaReq, opts ...grpc.CallOption) (*CheckCaptchaResponse, error)
	}

	defaultCaptchaService struct {
		cli zrpc.Client
	}
)

func NewCaptchaService(cli zrpc.Client) CaptchaService {
	return &defaultCaptchaService{
		cli: cli,
	}
}

func (m *defaultCaptchaService) GetCaptchaConfig(ctx context.Context, in *GetCaptchaConfigReq, opts ...grpc.CallOption) (*GetCaptchaConfigResponse, error) {
	client := pb.NewCaptchaServiceClient(m.cli.Conn())
	return client.GetCaptchaConfig(ctx, in, opts...)
}

func (m *defaultCaptchaService) CheckCaptcha(ctx context.Context, in *CheckCaptchaReq, opts ...grpc.CallOption) (*CheckCaptchaResponse, error) {
	client := pb.NewCaptchaServiceClient(m.cli.Conn())
	return client.CheckCaptcha(ctx, in, opts...)
}
