// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package captchaservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq       = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp      = pb.ApplyStudentVerifyResp
	CanParticipateReq           = pb.CanParticipateReq
	CanParticipateResp          = pb.CanParticipateResp
	CanPublishReq               = pb.CanPublishReq
	CanPublishResp              = pb.CanPublishResp
	CancelStudentVerifyReq      = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp     = pb.CancelStudentVerifyResp
	CaptchaArgs                 = pb.CaptchaArgs
	CheckCaptchaReq             = pb.CheckCaptchaReq
	CheckCaptchaResponse        = pb.CheckCaptchaResponse
	CheckQQEmailReq             = pb.CheckQQEmailReq
	CheckQQEmailResponse        = pb.CheckQQEmailResponse
	CheckUserExistsReq          = pb.CheckUserExistsReq
	CheckUserExistsResponse     = pb.CheckUserExistsResponse
	ConfirmStudentVerifyReq     = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp    = pb.ConfirmStudentVerifyResp
	CreditLogItem               = pb.CreditLogItem
	DeleteUserReq               = pb.DeleteUserReq
	DeleteUserResponse          = pb.DeleteUserResponse
	ForgetPasswordReq           = pb.ForgetPasswordReq
	ForgetPasswordResponse      = pb.ForgetPasswordResponse
	GetAllInterestTagsReq       = pb.GetAllInterestTagsReq
	GetAllInterestTagsResp      = pb.GetAllInterestTagsResp
	GetAllTagsReq               = pb.GetAllTagsReq
	GetAllTagsResp              = pb.GetAllTagsResp
	GetCaptchaConfigReq         = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse    = pb.GetCaptchaConfigResponse
	GetCreditInfoReq            = pb.GetCreditInfoReq
	GetCreditInfoResp           = pb.GetCreditInfoResp
	GetCreditLogsReq            = pb.GetCreditLogsReq
	GetCreditLogsResp           = pb.GetCreditLogsResp
	GetGroupUserReq             = pb.GetGroupUserReq
	GetGroupUserResponse        = pb.GetGroupUserResponse
	GetSysImageReq              = pb.GetSysImageReq
	GetSysImageResp             = pb.GetSysImageResp
	GetTagsByIdsReq             = pb.GetTagsByIdsReq
	GetTagsByIdsResp            = pb.GetTagsByIdsResp
	GetUserHomeReq              = pb.GetUserHomeReq
	GetUserHomeResp             = pb.GetUserHomeResp
	GetUserInfoReq              = pb.GetUserInfoReq
	GetUserInfoResponse         = pb.GetUserInfoResponse
	GetUserTagsReq              = pb.GetUserTagsReq
	GetUserTagsResponse         = pb.GetUserTagsResponse
	GetVerifyCurrentReq         = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp        = pb.GetVerifyCurrentResp
	GetVerifyInfoReq            = pb.GetVerifyInfoReq
	GetVerifyInfoResp           = pb.GetVerifyInfoResp
	GroupUserInfo               = pb.GroupUserInfo
	InitCreditReq               = pb.InitCreditReq
	InitCreditResp              = pb.InitCreditResp
	InterestTag                 = pb.InterestTag
	IsVerifiedReq               = pb.IsVerifiedReq
	IsVerifiedResp              = pb.IsVerifiedResp
	LoginReq                    = pb.LoginReq
	LoginResponse               = pb.LoginResponse
	LoginUserInfo               = pb.LoginUserInfo
	LogoutReq                   = pb.LogoutReq
	LogoutResponse              = pb.LogoutResponse
	ProcessOcrVerifyReq         = pb.ProcessOcrVerifyReq
	ProcessOcrVerifyResp        = pb.ProcessOcrVerifyResp
	RefreshReq                  = pb.RefreshReq
	RefreshResponse             = pb.RefreshResponse
	RegisterReq                 = pb.RegisterReq
	RegisterResponse            = pb.RegisterResponse
	SendQQEmailReq              = pb.SendQQEmailReq
	SendQQEmailResponse         = pb.SendQQEmailResponse
	TagBasicInfo                = pb.TagBasicInfo
	TagInfo                     = pb.TagInfo
	TagUsageCountReq            = pb.TagUsageCountReq
	TagUsageCountResp           = pb.TagUsageCountResp
	UpdatePasswordReq           = pb.UpdatePasswordReq
	UpdatePasswordResponse      = pb.UpdatePasswordResponse
	UpdateScoreReq              = pb.UpdateScoreReq
	UpdateScoreResp             = pb.UpdateScoreResp
	UpdateSysImageRefCountReq   = pb.UpdateSysImageRefCountReq
	UpdateSysImageRefCountResp  = pb.UpdateSysImageRefCountResp
	UpdateUserInfoReq           = pb.UpdateUserInfoReq
	UpdateUserInfoResponse      = pb.UpdateUserInfoResponse
	UpdateUserTagReq            = pb.UpdateUserTagReq
	UpdateUserTagResponse       = pb.UpdateUserTagResponse
	UpdateVerifyStatusReq       = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp      = pb.UpdateVerifyStatusResp
	UploadActivityCoverReq      = pb.UploadActivityCoverReq
	UploadActivityCoverResp     = pb.UploadActivityCoverResp
	UploadAvatarReq             = pb.UploadAvatarReq
	UploadAvatarResp            = pb.UploadAvatarResp
	UploadStudentCardImagesReq  = pb.UploadStudentCardImagesReq
	UploadStudentCardImagesResp = pb.UploadStudentCardImagesResp
	UploadSysImageReq           = pb.UploadSysImageReq
	UploadSysImageResp          = pb.UploadSysImageResp
	UserHomeActivityItem        = pb.UserHomeActivityItem
	UserHomeActivityList        = pb.UserHomeActivityList
	UserHomeInfo                = pb.UserHomeInfo
	UserHomeTag                 = pb.UserHomeTag
	UserInfo                    = pb.UserInfo
	UserTag                     = pb.UserTag
	VerifyModifiedData          = pb.VerifyModifiedData
	VerifyOcrData               = pb.VerifyOcrData

	CaptchaService interface {
		GetCaptchaConfig(ctx context.Context, in *GetCaptchaConfigReq, opts ...grpc.CallOption) (*GetCaptchaConfigResponse, error)
		CheckCaptcha(ctx context.Context, in *CheckCaptchaReq, opts ...grpc.CallOption) (*CheckCaptchaResponse, error)
	}

	defaultCaptchaService struct {
		cli zrpc.Client
	}
)

func NewCaptchaService(cli zrpc.Client) CaptchaService {
	return &defaultCaptchaService{
		cli: cli,
	}
}

func (m *defaultCaptchaService) GetCaptchaConfig(ctx context.Context, in *GetCaptchaConfigReq, opts ...grpc.CallOption) (*GetCaptchaConfigResponse, error) {
	client := pb.NewCaptchaServiceClient(m.cli.Conn())
	return client.GetCaptchaConfig(ctx, in, opts...)
}

func (m *defaultCaptchaService) CheckCaptcha(ctx context.Context, in *CheckCaptchaReq, opts ...grpc.CallOption) (*CheckCaptchaResponse, error) {
	client := pb.NewCaptchaServiceClient(m.cli.Conn())
	return client.CheckCaptcha(ctx, in, opts...)
}
