// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package activityservice

import (
	"context"

	"activity-platform/app/activity/rpc/activity"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActivityDetail                 = activity.ActivityDetail
	ActivityListItem               = activity.ActivityListItem
	ActivityListItems              = activity.ActivityListItems
	ApproveActivityReq             = activity.ApproveActivityReq
	ApproveActivityResp            = activity.ApproveActivityResp
	BatchGetActivityBasicReq       = activity.BatchGetActivityBasicReq
	BatchGetActivityBasicResp      = activity.BatchGetActivityBasicResp
	CancelActivityReq              = activity.CancelActivityReq
	CancelActivityRequest          = activity.CancelActivityRequest
	CancelActivityResp             = activity.CancelActivityResp
	CancelActivityResponse         = activity.CancelActivityResponse
	Category                       = activity.Category
	CreateActivityActionReq        = activity.CreateActivityActionReq
	CreateActivityActionResp       = activity.CreateActivityActionResp
	CreateActivityCompensateReq    = activity.CreateActivityCompensateReq
	CreateActivityCompensateResp   = activity.CreateActivityCompensateResp
	CreateActivityReq              = activity.CreateActivityReq
	CreateActivityResp             = activity.CreateActivityResp
	DeleteActivityActionReq        = activity.DeleteActivityActionReq
	DeleteActivityActionResp       = activity.DeleteActivityActionResp
	DeleteActivityCompensateReq    = activity.DeleteActivityCompensateReq
	DeleteActivityCompensateResp   = activity.DeleteActivityCompensateResp
	DeleteActivityReq              = activity.DeleteActivityReq
	DeleteActivityResp             = activity.DeleteActivityResp
	GetActivityBasicReq            = activity.GetActivityBasicReq
	GetActivityBasicResp           = activity.GetActivityBasicResp
	GetActivityListRequest         = activity.GetActivityListRequest
	GetActivityListResponse        = activity.GetActivityListResponse
	GetActivityReq                 = activity.GetActivityReq
	GetActivityResp                = activity.GetActivityResp
	GetHotActivitiesReq            = activity.GetHotActivitiesReq
	GetHotActivitiesResp           = activity.GetHotActivitiesResp
	GetRegisteredCountRequest      = activity.GetRegisteredCountRequest
	GetRegisteredCountResponse     = activity.GetRegisteredCountResponse
	GetTicketDetailRequest         = activity.GetTicketDetailRequest
	GetTicketDetailResponse        = activity.GetTicketDetailResponse
	GetTicketListRequest           = activity.GetTicketListRequest
	GetTicketListResponse          = activity.GetTicketListResponse
	GetUserPublishedActivitiesReq  = activity.GetUserPublishedActivitiesReq
	GetUserPublishedActivitiesResp = activity.GetUserPublishedActivitiesResp
	IncrViewCountReq               = activity.IncrViewCountReq
	IncrViewCountResp              = activity.IncrViewCountResp
	ListActivitiesReq              = activity.ListActivitiesReq
	ListActivitiesResp             = activity.ListActivitiesResp
	ListCategoriesReq              = activity.ListCategoriesReq
	ListCategoriesResp             = activity.ListCategoriesResp
	ListTagsReq                    = activity.ListTagsReq
	ListTagsResp                   = activity.ListTagsResp
	Pagination                     = activity.Pagination
	RegisterActivityRequest        = activity.RegisterActivityRequest
	RegisterActivityResponse       = activity.RegisterActivityResponse
	RejectActivityReq              = activity.RejectActivityReq
	RejectActivityResp             = activity.RejectActivityResp
	SearchActivitiesReq            = activity.SearchActivitiesReq
	SearchActivitiesResp           = activity.SearchActivitiesResp
	SubmitActivityReq              = activity.SubmitActivityReq
	SubmitActivityResp             = activity.SubmitActivityResp
	Tag                            = activity.Tag
	TicketListItem                 = activity.TicketListItem
	UpdateActivityReq              = activity.UpdateActivityReq
	UpdateActivityResp             = activity.UpdateActivityResp
	VerifyTicketRequest            = activity.VerifyTicketRequest
	VerifyTicketResponse           = activity.VerifyTicketResponse

	ActivityService interface {
		// RegisterActivity 报名活动
		RegisterActivity(ctx context.Context, in *RegisterActivityRequest, opts ...grpc.CallOption) (*RegisterActivityResponse, error)
		// CancelActivities 取消报名活动
		CancelActivities(ctx context.Context, in *CancelActivityRequest, opts ...grpc.CallOption) (*CancelActivityResponse, error)
		// GetActivityList 获取待参加/已参加活动信息列表
		GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error)
		// VerifyTicket 核销票券
		VerifyTicket(ctx context.Context, in *VerifyTicketRequest, opts ...grpc.CallOption) (*VerifyTicketResponse, error)
		// GetTicketList 获取个人票券列表
		GetTicketList(ctx context.Context, in *GetTicketListRequest, opts ...grpc.CallOption) (*GetTicketListResponse, error)
		// GetTicketDetail 获取票券详情
		GetTicketDetail(ctx context.Context, in *GetTicketDetailRequest, opts ...grpc.CallOption) (*GetTicketDetailResponse, error)
		// GetRegisteredCount 获取报名数量
		GetRegisteredCount(ctx context.Context, in *GetRegisteredCountRequest, opts ...grpc.CallOption) (*GetRegisteredCountResponse, error)
		// ==================== CRUD 接口 ====================
		CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error)
		UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error)
		DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error)
		GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error)
		ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error)
		// ==================== 状态操作接口 ====================
		SubmitActivity(ctx context.Context, in *SubmitActivityReq, opts ...grpc.CallOption) (*SubmitActivityResp, error)
		ApproveActivity(ctx context.Context, in *ApproveActivityReq, opts ...grpc.CallOption) (*ApproveActivityResp, error)
		RejectActivity(ctx context.Context, in *RejectActivityReq, opts ...grpc.CallOption) (*RejectActivityResp, error)
		CancelActivity(ctx context.Context, in *CancelActivityReq, opts ...grpc.CallOption) (*CancelActivityResp, error)
		// ==================== 搜索接口 ====================
		SearchActivities(ctx context.Context, in *SearchActivitiesReq, opts ...grpc.CallOption) (*SearchActivitiesResp, error)
		GetHotActivities(ctx context.Context, in *GetHotActivitiesReq, opts ...grpc.CallOption) (*GetHotActivitiesResp, error)
		// ==================== 分类标签接口 ====================
		ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error)
		ListTags(ctx context.Context, in *ListTagsReq, opts ...grpc.CallOption) (*ListTagsResp, error)
		// ==================== 浏览量接口 ====================
		IncrViewCount(ctx context.Context, in *IncrViewCountReq, opts ...grpc.CallOption) (*IncrViewCountResp, error)
		// ==================== 内部接口（供其他微服务调用）====================
		GetActivityBasic(ctx context.Context, in *GetActivityBasicReq, opts ...grpc.CallOption) (*GetActivityBasicResp, error)
		// 批量获取活动基本信息
		BatchGetActivityBasic(ctx context.Context, in *BatchGetActivityBasicReq, opts ...grpc.CallOption) (*BatchGetActivityBasicResp, error)
		// 获取用户已发布的活动列表（User 服务调用，用于展示用户主页）
		GetUserPublishedActivities(ctx context.Context, in *GetUserPublishedActivitiesReq, opts ...grpc.CallOption) (*GetUserPublishedActivitiesResp, error)
	}

	defaultActivityService struct {
		cli zrpc.Client
	}
)

func NewActivityService(cli zrpc.Client) ActivityService {
	return &defaultActivityService{
		cli: cli,
	}
}

// RegisterActivity 报名活动
func (m *defaultActivityService) RegisterActivity(ctx context.Context, in *RegisterActivityRequest, opts ...grpc.CallOption) (*RegisterActivityResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.RegisterActivity(ctx, in, opts...)
}

// CancelActivities 取消报名活动
func (m *defaultActivityService) CancelActivities(ctx context.Context, in *CancelActivityRequest, opts ...grpc.CallOption) (*CancelActivityResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.CancelActivities(ctx, in, opts...)
}

// GetActivityList 获取待参加/已参加活动信息列表
func (m *defaultActivityService) GetActivityList(ctx context.Context, in *GetActivityListRequest, opts ...grpc.CallOption) (*GetActivityListResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetActivityList(ctx, in, opts...)
}

// VerifyTicket 核销票券
func (m *defaultActivityService) VerifyTicket(ctx context.Context, in *VerifyTicketRequest, opts ...grpc.CallOption) (*VerifyTicketResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.VerifyTicket(ctx, in, opts...)
}

// GetTicketList 获取个人票券列表
func (m *defaultActivityService) GetTicketList(ctx context.Context, in *GetTicketListRequest, opts ...grpc.CallOption) (*GetTicketListResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetTicketList(ctx, in, opts...)
}

// GetTicketDetail 获取票券详情
func (m *defaultActivityService) GetTicketDetail(ctx context.Context, in *GetTicketDetailRequest, opts ...grpc.CallOption) (*GetTicketDetailResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetTicketDetail(ctx, in, opts...)
}

// GetRegisteredCount 获取报名数量
func (m *defaultActivityService) GetRegisteredCount(ctx context.Context, in *GetRegisteredCountRequest, opts ...grpc.CallOption) (*GetRegisteredCountResponse, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetRegisteredCount(ctx, in, opts...)
}

// ==================== CRUD 接口 ====================
func (m *defaultActivityService) CreateActivity(ctx context.Context, in *CreateActivityReq, opts ...grpc.CallOption) (*CreateActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.CreateActivity(ctx, in, opts...)
}

func (m *defaultActivityService) UpdateActivity(ctx context.Context, in *UpdateActivityReq, opts ...grpc.CallOption) (*UpdateActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.UpdateActivity(ctx, in, opts...)
}

func (m *defaultActivityService) DeleteActivity(ctx context.Context, in *DeleteActivityReq, opts ...grpc.CallOption) (*DeleteActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.DeleteActivity(ctx, in, opts...)
}

func (m *defaultActivityService) GetActivity(ctx context.Context, in *GetActivityReq, opts ...grpc.CallOption) (*GetActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetActivity(ctx, in, opts...)
}

func (m *defaultActivityService) ListActivities(ctx context.Context, in *ListActivitiesReq, opts ...grpc.CallOption) (*ListActivitiesResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.ListActivities(ctx, in, opts...)
}

// ==================== 状态操作接口 ====================
func (m *defaultActivityService) SubmitActivity(ctx context.Context, in *SubmitActivityReq, opts ...grpc.CallOption) (*SubmitActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.SubmitActivity(ctx, in, opts...)
}

func (m *defaultActivityService) ApproveActivity(ctx context.Context, in *ApproveActivityReq, opts ...grpc.CallOption) (*ApproveActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.ApproveActivity(ctx, in, opts...)
}

func (m *defaultActivityService) RejectActivity(ctx context.Context, in *RejectActivityReq, opts ...grpc.CallOption) (*RejectActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.RejectActivity(ctx, in, opts...)
}

func (m *defaultActivityService) CancelActivity(ctx context.Context, in *CancelActivityReq, opts ...grpc.CallOption) (*CancelActivityResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.CancelActivity(ctx, in, opts...)
}

// ==================== 搜索接口 ====================
func (m *defaultActivityService) SearchActivities(ctx context.Context, in *SearchActivitiesReq, opts ...grpc.CallOption) (*SearchActivitiesResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.SearchActivities(ctx, in, opts...)
}

func (m *defaultActivityService) GetHotActivities(ctx context.Context, in *GetHotActivitiesReq, opts ...grpc.CallOption) (*GetHotActivitiesResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetHotActivities(ctx, in, opts...)
}

// ==================== 分类标签接口 ====================
func (m *defaultActivityService) ListCategories(ctx context.Context, in *ListCategoriesReq, opts ...grpc.CallOption) (*ListCategoriesResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.ListCategories(ctx, in, opts...)
}

func (m *defaultActivityService) ListTags(ctx context.Context, in *ListTagsReq, opts ...grpc.CallOption) (*ListTagsResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.ListTags(ctx, in, opts...)
}

// ==================== 浏览量接口 ====================
func (m *defaultActivityService) IncrViewCount(ctx context.Context, in *IncrViewCountReq, opts ...grpc.CallOption) (*IncrViewCountResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.IncrViewCount(ctx, in, opts...)
}

// ==================== 内部接口（供其他微服务调用）====================
func (m *defaultActivityService) GetActivityBasic(ctx context.Context, in *GetActivityBasicReq, opts ...grpc.CallOption) (*GetActivityBasicResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetActivityBasic(ctx, in, opts...)
}

// 批量获取活动基本信息
func (m *defaultActivityService) BatchGetActivityBasic(ctx context.Context, in *BatchGetActivityBasicReq, opts ...grpc.CallOption) (*BatchGetActivityBasicResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.BatchGetActivityBasic(ctx, in, opts...)
}

// 获取用户已发布的活动列表（User 服务调用，用于展示用户主页）
func (m *defaultActivityService) GetUserPublishedActivities(ctx context.Context, in *GetUserPublishedActivitiesReq, opts ...grpc.CallOption) (*GetUserPublishedActivitiesResp, error) {
	client := activity.NewActivityServiceClient(m.cli.Conn())
	return client.GetUserPublishedActivities(ctx, in, opts...)
}
