// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package verifyservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CanParticipateReq      = pb.CanParticipateReq
	CanParticipateResp     = pb.CanParticipateResp
	CanPublishReq          = pb.CanPublishReq
	CanPublishResp         = pb.CanPublishResp
	GetCreditInfoReq       = pb.GetCreditInfoReq
	GetCreditInfoResp      = pb.GetCreditInfoResp
	InitCreditReq          = pb.InitCreditReq
	InitCreditResp         = pb.InitCreditResp
	IsVerifiedReq          = pb.IsVerifiedReq
	IsVerifiedResp         = pb.IsVerifiedResp
	UpdateScoreReq         = pb.UpdateScoreReq
	UpdateScoreResp        = pb.UpdateScoreResp
	UpdateVerifyStatusReq  = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp = pb.UpdateVerifyStatusResp
	VerifyOcrData          = pb.VerifyOcrData

	VerifyService interface {
		// IsVerified 查询用户是否已完成学生认证
		IsVerified(ctx context.Context, in *IsVerifiedReq, opts ...grpc.CallOption) (*IsVerifiedResp, error)
		// UpdateVerifyStatus 更新认证状态
		UpdateVerifyStatus(ctx context.Context, in *UpdateVerifyStatusReq, opts ...grpc.CallOption) (*UpdateVerifyStatusResp, error)
	}

	defaultVerifyService struct {
		cli zrpc.Client
	}
)

func NewVerifyService(cli zrpc.Client) VerifyService {
	return &defaultVerifyService{
		cli: cli,
	}
}

// IsVerified 查询用户是否已完成学生认证
func (m *defaultVerifyService) IsVerified(ctx context.Context, in *IsVerifiedReq, opts ...grpc.CallOption) (*IsVerifiedResp, error) {
	client := pb.NewVerifyServiceClient(m.cli.Conn())
	return client.IsVerified(ctx, in, opts...)
}

// UpdateVerifyStatus 更新认证状态
func (m *defaultVerifyService) UpdateVerifyStatus(ctx context.Context, in *UpdateVerifyStatusReq, opts ...grpc.CallOption) (*UpdateVerifyStatusResp, error) {
	client := pb.NewVerifyServiceClient(m.cli.Conn())
	return client.UpdateVerifyStatus(ctx, in, opts...)
}
