// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyVerifyReq struct {
	RealName      string `form:"real_name"`
	SchoolName    string `form:"school_name"`
	StudentId     string `form:"student_id"`
	Department    string `form:"department"`
	AdmissionYear string `form:"admission_year"`
}

type ApplyVerifyResp struct {
	VerifyId   int64  `json:"verify_id"`
	Status     int32  `json:"status"`
	StatusDesc string `json:"status_desc"`
	CreatedAt  string `json:"created_at"`
}

type CancelVerifyReq struct {
	VerifyId     int64  `json:"verify_id"`
	CancelReason string `json:"cancel_reason,optional"`
}

type CancelVerifyResp struct {
	VerifyId      int64  `json:"verify_id"`
	NewStatus     int32  `json:"new_status"`
	NewStatusDesc string `json:"new_status_desc"`
}

type ChangePasswordReq struct {
	OriginPassword string `json:"originPassword"`
	NewPassword    string `json:"newPassword"`
}

type ChangePasswordResp struct {
	Success bool `json:"success"`
}

type ConfirmVerifyReq struct {
	VerifyId     int64         `json:"verify_id"`
	IsConfirmed  bool          `json:"is_confirmed"`
	ModifiedData *ModifiedData `json:"modified_data,optional"`
}

type ConfirmVerifyResp struct {
	VerifyId      int64  `json:"verify_id"`
	NewStatus     int32  `json:"new_status"`
	NewStatusDesc string `json:"new_status_desc"`
}

type CreditLogItem struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"user_id"`
	ChangeType     int32  `json:"change_type"`
	ChangeTypeName string `json:"change_type_name"`
	Delta          int32  `json:"delta"`
	SourceId       string `json:"source_id"`
	Reason         string `json:"reason"`
	CreatedAt      int64  `json:"created_at"`
}

type ForgetPasswordReq struct {
	QqCode      string `json:"qq_code"`
	NewPassword string `json:"new_password"`
}

type ForgetPasswordResp struct {
	Success bool `json:"success"`
}

type GetCaptchaResp struct {
	CaptchaId string `json:"captchaId"`
}

type GetCodeResp struct {
}

type GetCreditLogsReq struct {
	ChangeType int32 `form:"change_type,optional"`
	StartTime  int64 `form:"start_time,optional"`
	EndTime    int64 `form:"end_time,optional"`
	Page       int32 `form:"page,optional,default=1"`
	PageSize   int32 `form:"page_size,optional,default=20"`
}

type GetCreditLogsResp struct {
	List     []CreditLogItem `json:"list"`
	Total    int64           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetForgetPasswordCodeReq struct {
	QqEmail string `form:"qq_email"`
}

type GetInterestTagsResp struct {
	InterestTags []InterestTag `json:"interestTags"`
}

type GetRegisterCodeReq struct {
	QqEmail string `form:"qq_email"`
}

type GetUserHomeReq struct {
	UserId            int64 `path:"user_id"`
	JoinedPage        int32 `form:"joined_page,optional,default=1"`
	JoinedPageSize    int32 `form:"joined_page_size,optional,default=10"`
	PublishedPage     int32 `form:"published_page,optional,default=1"`
	PublishedPageSize int32 `form:"published_page_size,optional,default=10"`
}

type GetUserHomeResp struct {
	UserInfo            UserHomeInfo         `json:"userInfo"`
	Tags                []InterestTag        `json:"tags"`
	JoinedActivities    UserHomeActivityList `json:"joinedActivities"`
	PublishedActivities UserHomeActivityList `json:"publishedActivities"`
}

type GetVerifyCurrentResp struct {
	HasRecord    bool        `json:"has_record"`
	VerifyId     int64       `json:"verify_id"`
	Status       int32       `json:"status"`
	StatusDesc   string      `json:"status_desc"`
	CanApply     bool        `json:"can_apply"`
	CanConfirm   bool        `json:"can_confirm"`
	CanCancel    bool        `json:"can_cancel"`
	NeedAction   string      `json:"need_action"`
	VerifyData   *VerifyData `json:"verify_data,optional"`
	RejectReason string      `json:"reject_reason,optional"`
	CreatedAt    string      `json:"created_at,optional"`
	UpdatedAt    string      `json:"updated_at,optional"`
}

type InterestTag struct {
	Id       int64  `json:"id"`
	TagName  string `json:"tagName"`
	TagColor string `json:"tagColor"`
	TagIcon  string `json:"tagIcon"`
	TagDesc  string `json:"tagDesc"`
}

type LoginReq struct {
	QqEmail       string `json:"qqEmail"`
	Password      string `json:"password"`
	LotNumber     string `json:"lotNumber"`
	CaptchaOutput string `json:"captchaOutput"`
	PassToken     string `json:"passToken"`
	GenTime       string `json:"genTime"`
}

type LoginResp struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	UserInfo     UserInfo `json:"userInfo"`
}

type LogoffReq struct {
	QqCode string `json:"qq_code"`
}

type LogoffResp struct {
	Success bool `json:"success"`
}

type ModifiedData struct {
	RealName      string `json:"real_name,optional"`
	SchoolName    string `json:"school_name,optional"`
	StudentId     string `json:"student_id,optional"`
	Department    string `json:"department,optional"`
	AdmissionYear string `json:"admission_year,optional"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResp struct {
	AccessToken string `json:"accessToken"`
}

type RegisterReq struct {
	QqEmail  string `json:"qqEmail"`
	QqCode   string `json:"qqCode"`
	Password string `json:"password"`
	Nickname string `json:"nickname"`
}

type RegisterResp struct {
	AccessToken  string   `json:"accessToken"`
	RefreshToken string   `json:"refreshToken"`
	UserInfo     UserInfo `json:"userInfo"`
}

type UpdateInterestReq struct {
	InterestTagIds []int64 `json:"interestTagIds"`
}

type UpdateInterestResp struct {
	UserId       int64         `json:"userId"`
	InterestTags []InterestTag `json:"interestTags"`
}

type UpdateUserInfoReq struct {
	Age            int64   `form:"age,optional"`
	Nickname       string  `form:"nickname,optional"`
	Introduction   string  `form:"introduction,optional"`
	Gender         string  `form:"gender,optional"`
	AvatarId       int64   `form:"avatarId,optional"`
	InterestTagIds []int64 `form:"interestTagIds,optional"`
}

type UpdateUserInfoResp struct {
	UserInfo
}

type UploadSysImageReq struct {
	BizType string `form:"bizType"` // avatar/activity_cover/identity_auth
}

type UploadSysImageResp struct {
	Id int64 `json:"id"`
}

type UserHomeActivityItem struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Time     string `json:"time"`
	Status   string `json:"status"`
	ImageUrl string `json:"imageUrl"`
}

type UserHomeActivityList struct {
	Total int32                  `json:"total"`
	List  []UserHomeActivityItem `json:"list"`
}

type UserHomeInfo struct {
	UserId       int64  `json:"userId"`
	Nickname     string `json:"nickname"`
	AvatarUrl    string `json:"avatarUrl"`
	Introduction string `json:"introduction"`
	Gender       int32  `json:"gender"`
	Age          int32  `json:"age"`
}

type UserInfo struct {
	UserId            int64         `json:"userId"`
	Nickname          string        `json:"nickname"`
	AvatarUrl         string        `json:"avatarUrl"`
	Introduction      string        `json:"introduction"`
	Gender            string        `json:"gender"`
	Age               string        `json:"age"`
	ActivitiesNum     int64         `json:"activitiesNum"`
	InitiateNum       int64         `json:"initiateNum"`
	Credit            int64         `json:"credit"`
	IsStudentVerified bool          `json:"isStudentVerified"`
	InterestTags      []InterestTag `json:"interestTags"`
	QqEmail           string        `json:"qqEmail"`
}

type VerifyCaptchaReq struct {
	LotNumber     string `json:"lotNumber"`
	CaptchaOutput string `json:"captchaOutput"`
	PassToken     string `json:"passToken"`
	GenTime       string `json:"genTime"`
}

type VerifyCaptchaResp struct {
	IsValid bool `json:"isValid"`
}

type VerifyData struct {
	RealName      string `json:"real_name"`
	SchoolName    string `json:"school_name"`
	StudentId     string `json:"student_id"`
	Department    string `json:"department"`
	AdmissionYear string `json:"admission_year"`
	VerifiedAt    string `json:"verified_at,optional"`
}
