// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Modified: JSON tags changed to snake_case

package types

type ApplyVerifyReq struct {
	RealName      string `json:"real_name"`
	SchoolName    string `json:"school_name"`
	StudentId     string `json:"student_id"`
	Department    string `json:"department,optional"`
	AdmissionYear string `json:"admission_year"`
	FrontImageUrl string `json:"front_image_url"`
	BackImageUrl  string `json:"back_image_url"`
}

type ApplyVerifyResp struct {
	VerifyId   int64  `json:"verify_id"`
	Status     int32  `json:"status"`
	StatusDesc string `json:"status_desc"`
	CreatedAt  string `json:"created_at"`
}

type CancelVerifyReq struct {
	VerifyId     int64  `json:"verify_id"`
	CancelReason string `json:"cancel_reason,optional"`
}

type CancelVerifyResp struct {
	VerifyId      int64  `json:"verify_id"`
	NewStatus     int32  `json:"new_status"`
	NewStatusDesc string `json:"new_status_desc"`
}

type ConfirmVerifyReq struct {
	VerifyId     int64         `json:"verify_id"`
	IsConfirmed  bool          `json:"is_confirmed"`
	ModifiedData *ModifiedData `json:"modified_data,optional"`
}

type ConfirmVerifyResp struct {
	VerifyId      int64  `json:"verify_id"`
	NewStatus     int32  `json:"new_status"`
	NewStatusDesc string `json:"new_status_desc"`
}

type CreditLogItem struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"user_id"`
	ChangeType     int32  `json:"change_type"`
	ChangeTypeName string `json:"change_type_name"`
	Delta          int32  `json:"delta"`
	SourceId       string `json:"source_id"`
	Reason         string `json:"reason"`
	CreatedAt      int64  `json:"created_at"`
}

type GetCreditLogsReq struct {
	ChangeType int32 `form:"change_type,optional"`
	StartTime  int64 `form:"start_time,optional"`
	EndTime    int64 `form:"end_time,optional"`
	Page       int32 `form:"page,optional,default=1"`
	PageSize   int32 `form:"page_size,optional,default=20"`
}

type GetCreditLogsResp struct {
	List     []CreditLogItem `json:"list"`
	Total    int64           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"page_size"`
}

type GetVerifyCurrentResp struct {
	HasRecord    bool        `json:"has_record"`
	VerifyId     int64       `json:"verify_id"`
	Status       int32       `json:"status"`
	StatusDesc   string      `json:"status_desc"`
	CanApply     bool        `json:"can_apply"`
	CanConfirm   bool        `json:"can_confirm"`
	CanCancel    bool        `json:"can_cancel"`
	NeedAction   string      `json:"need_action"`
	VerifyData   *VerifyData `json:"verify_data,optional"`
	RejectReason string      `json:"reject_reason,optional"`
	CreatedAt    string      `json:"created_at,optional"`
	UpdatedAt    string      `json:"updated_at,optional"`
}

type ModifiedData struct {
	RealName      string `json:"real_name,optional"`
	SchoolName    string `json:"school_name,optional"`
	StudentId     string `json:"student_id,optional"`
	Department    string `json:"department,optional"`
	AdmissionYear string `json:"admission_year,optional"`
}

type VerifyData struct {
	RealName      string `json:"real_name"`
	SchoolName    string `json:"school_name"`
	StudentId     string `json:"student_id"`
	Department    string `json:"department"`
	AdmissionYear string `json:"admission_year"`
	VerifiedAt    string `json:"verified_at,optional"`
}
