// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApplyVerifyReq struct {
	RealName      string `json:"realName"`
	SchoolName    string `json:"schoolName"`
	StudentId     string `json:"studentId"`
	Department    string `json:"department,optional"`
	AdmissionYear string `json:"admissionYear"`
	FrontImageUrl string `json:"frontImageUrl"`
	BackImageUrl  string `json:"backImageUrl"`
}

type ApplyVerifyResp struct {
	VerifyId   int64  `json:"verifyId"`
	Status     int32  `json:"status"`
	StatusDesc string `json:"statusDesc"`
	CreatedAt  string `json:"createdAt"`
}

type CancelVerifyReq struct {
	VerifyId     int64  `json:"verifyId"`
	CancelReason string `json:"cancelReason,optional"`
}

type CancelVerifyResp struct {
	VerifyId      int64  `json:"verifyId"`
	NewStatus     int32  `json:"newStatus"`
	NewStatusDesc string `json:"newStatusDesc"`
}

type ConfirmVerifyReq struct {
	VerifyId     int64         `json:"verifyId"`
	IsConfirmed  bool          `json:"isConfirmed"`
	ModifiedData *ModifiedData `json:"modifiedData,optional"`
}

type ConfirmVerifyResp struct {
	VerifyId      int64  `json:"verifyId"`
	NewStatus     int32  `json:"newStatus"`
	NewStatusDesc string `json:"newStatusDesc"`
}

type CreditLogItem struct {
	Id             int64  `json:"id"`
	UserId         int64  `json:"userId"`
	ChangeType     int32  `json:"changeType"`
	ChangeTypeName string `json:"changeTypeName"`
	Delta          int32  `json:"delta"`
	SourceId       string `json:"sourceId"`
	Reason         string `json:"reason"`
	CreatedAt      int64  `json:"createdAt"`
}

type GetCreditLogsReq struct {
	ChangeType int32 `form:"changeType,optional"`
	StartTime  int64 `form:"startTime,optional"`
	EndTime    int64 `form:"endTime,optional"`
	Page       int32 `form:"page,optional,default=1"`
	PageSize   int32 `form:"pageSize,optional,default=20"`
}

type GetCreditLogsResp struct {
	List     []CreditLogItem `json:"list"`
	Total    int64           `json:"total"`
	Page     int32           `json:"page"`
	PageSize int32           `json:"pageSize"`
}

type GetVerifyCurrentResp struct {
	HasRecord    bool        `json:"hasRecord"`
	VerifyId     int64       `json:"verifyId"`
	Status       int32       `json:"status"`
	StatusDesc   string      `json:"statusDesc"`
	CanApply     bool        `json:"canApply"`
	CanConfirm   bool        `json:"canConfirm"`
	CanCancel    bool        `json:"canCancel"`
	NeedAction   string      `json:"needAction"`
	VerifyData   *VerifyData `json:"verifyData,optional"`
	RejectReason string      `json:"rejectReason,optional"`
	CreatedAt    string      `json:"createdAt,optional"`
	UpdatedAt    string      `json:"updatedAt,optional"`
}

type ModifiedData struct {
	RealName      string `json:"realName,optional"`
	SchoolName    string `json:"schoolName,optional"`
	StudentId     string `json:"studentId,optional"`
	Department    string `json:"department,optional"`
	AdmissionYear string `json:"admissionYear,optional"`
}

type VerifyData struct {
	RealName      string `json:"realName"`
	SchoolName    string `json:"schoolName"`
	StudentId     string `json:"studentId"`
	Department    string `json:"department"`
	AdmissionYear string `json:"admissionYear"`
	VerifiedAt    string `json:"verifiedAt,optional"`
}
