// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package activitybranchservice

import (
	"context"

	"activity-platform/app/activity/rpc/activity"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ActivityDetail                 = activity.ActivityDetail
	ActivityListItem               = activity.ActivityListItem
	ActivityListItems              = activity.ActivityListItems
	ApproveActivityReq             = activity.ApproveActivityReq
	ApproveActivityResp            = activity.ApproveActivityResp
	BatchGetActivityBasicReq       = activity.BatchGetActivityBasicReq
	BatchGetActivityBasicResp      = activity.BatchGetActivityBasicResp
	CancelActivityReq              = activity.CancelActivityReq
	CancelActivityRequest          = activity.CancelActivityRequest
	CancelActivityResp             = activity.CancelActivityResp
	CancelActivityResponse         = activity.CancelActivityResponse
	Category                       = activity.Category
	CreateActivityActionReq        = activity.CreateActivityActionReq
	CreateActivityActionResp       = activity.CreateActivityActionResp
	CreateActivityCompensateReq    = activity.CreateActivityCompensateReq
	CreateActivityCompensateResp   = activity.CreateActivityCompensateResp
	CreateActivityReq              = activity.CreateActivityReq
	CreateActivityResp             = activity.CreateActivityResp
	DeleteActivityActionReq        = activity.DeleteActivityActionReq
	DeleteActivityActionResp       = activity.DeleteActivityActionResp
	DeleteActivityCompensateReq    = activity.DeleteActivityCompensateReq
	DeleteActivityCompensateResp   = activity.DeleteActivityCompensateResp
	DeleteActivityReq              = activity.DeleteActivityReq
	DeleteActivityResp             = activity.DeleteActivityResp
	GetActivityBasicReq            = activity.GetActivityBasicReq
	GetActivityBasicResp           = activity.GetActivityBasicResp
	GetActivityListRequest         = activity.GetActivityListRequest
	GetActivityListResponse        = activity.GetActivityListResponse
	GetActivityReq                 = activity.GetActivityReq
	GetActivityResp                = activity.GetActivityResp
	GetHotActivitiesReq            = activity.GetHotActivitiesReq
	GetHotActivitiesResp           = activity.GetHotActivitiesResp
	GetRegisteredCountRequest      = activity.GetRegisteredCountRequest
	GetRegisteredCountResponse     = activity.GetRegisteredCountResponse
	GetTicketDetailRequest         = activity.GetTicketDetailRequest
	GetTicketDetailResponse        = activity.GetTicketDetailResponse
	GetTicketListRequest           = activity.GetTicketListRequest
	GetTicketListResponse          = activity.GetTicketListResponse
	GetUserPublishedActivitiesReq  = activity.GetUserPublishedActivitiesReq
	GetUserPublishedActivitiesResp = activity.GetUserPublishedActivitiesResp
	IncrViewCountReq               = activity.IncrViewCountReq
	IncrViewCountResp              = activity.IncrViewCountResp
	ListActivitiesReq              = activity.ListActivitiesReq
	ListActivitiesResp             = activity.ListActivitiesResp
	ListCategoriesReq              = activity.ListCategoriesReq
	ListCategoriesResp             = activity.ListCategoriesResp
	ListTagsReq                    = activity.ListTagsReq
	ListTagsResp                   = activity.ListTagsResp
	Pagination                     = activity.Pagination
	RegisterActivityRequest        = activity.RegisterActivityRequest
	RegisterActivityResponse       = activity.RegisterActivityResponse
	RejectActivityReq              = activity.RejectActivityReq
	RejectActivityResp             = activity.RejectActivityResp
	SearchActivitiesReq            = activity.SearchActivitiesReq
	SearchActivitiesResp           = activity.SearchActivitiesResp
	SubmitActivityReq              = activity.SubmitActivityReq
	SubmitActivityResp             = activity.SubmitActivityResp
	Tag                            = activity.Tag
	TicketListItem                 = activity.TicketListItem
	UpdateActivityReq              = activity.UpdateActivityReq
	UpdateActivityResp             = activity.UpdateActivityResp
	VerifyTicketRequest            = activity.VerifyTicketRequest
	VerifyTicketResponse           = activity.VerifyTicketResponse

	ActivityBranchService interface {
		// 创建活动 - 正向操作
		CreateActivityAction(ctx context.Context, in *CreateActivityActionReq, opts ...grpc.CallOption) (*CreateActivityActionResp, error)
		// 创建活动 - 补偿操作（回滚）
		CreateActivityCompensate(ctx context.Context, in *CreateActivityCompensateReq, opts ...grpc.CallOption) (*CreateActivityCompensateResp, error)
		// 删除活动 - 正向操作
		DeleteActivityAction(ctx context.Context, in *DeleteActivityActionReq, opts ...grpc.CallOption) (*DeleteActivityActionResp, error)
		// 删除活动 - 补偿操作（回滚）
		DeleteActivityCompensate(ctx context.Context, in *DeleteActivityCompensateReq, opts ...grpc.CallOption) (*DeleteActivityCompensateResp, error)
	}

	defaultActivityBranchService struct {
		cli zrpc.Client
	}
)

func NewActivityBranchService(cli zrpc.Client) ActivityBranchService {
	return &defaultActivityBranchService{
		cli: cli,
	}
}

// 创建活动 - 正向操作
func (m *defaultActivityBranchService) CreateActivityAction(ctx context.Context, in *CreateActivityActionReq, opts ...grpc.CallOption) (*CreateActivityActionResp, error) {
	client := activity.NewActivityBranchServiceClient(m.cli.Conn())
	return client.CreateActivityAction(ctx, in, opts...)
}

// 创建活动 - 补偿操作（回滚）
func (m *defaultActivityBranchService) CreateActivityCompensate(ctx context.Context, in *CreateActivityCompensateReq, opts ...grpc.CallOption) (*CreateActivityCompensateResp, error) {
	client := activity.NewActivityBranchServiceClient(m.cli.Conn())
	return client.CreateActivityCompensate(ctx, in, opts...)
}

// 删除活动 - 正向操作
func (m *defaultActivityBranchService) DeleteActivityAction(ctx context.Context, in *DeleteActivityActionReq, opts ...grpc.CallOption) (*DeleteActivityActionResp, error) {
	client := activity.NewActivityBranchServiceClient(m.cli.Conn())
	return client.DeleteActivityAction(ctx, in, opts...)
}

// 删除活动 - 补偿操作（回滚）
func (m *defaultActivityBranchService) DeleteActivityCompensate(ctx context.Context, in *DeleteActivityCompensateReq, opts ...grpc.CallOption) (*DeleteActivityCompensateResp, error) {
	client := activity.NewActivityBranchServiceClient(m.cli.Conn())
	return client.DeleteActivityCompensate(ctx, in, opts...)
}
