// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"activity-platform/app/user/rpc/internal/logic/captchaservice"
	"activity-platform/app/user/rpc/internal/svc"
	"activity-platform/app/user/rpc/pb/pb"
)

type CaptchaServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCaptchaServiceServer
}

func NewCaptchaServiceServer(svcCtx *svc.ServiceContext) *CaptchaServiceServer {
	return &CaptchaServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CaptchaServiceServer) GetCaptchaConfig(ctx context.Context, in *pb.GetCaptchaConfigReq) (*pb.GetCaptchaConfigResponse, error) {
	l := captchaservicelogic.NewGetCaptchaConfigLogic(ctx, s.svcCtx)
	return l.GetCaptchaConfig(in)
}

func (s *CaptchaServiceServer) CheckCaptcha(ctx context.Context, in *pb.CheckCaptchaReq) (*pb.CheckCaptchaResponse, error) {
	l := captchaservicelogic.NewCheckCaptchaLogic(ctx, s.svcCtx)
	return l.CheckCaptcha(in)
}
