// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package uploadtoqiniu

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq    = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp   = pb.ApplyStudentVerifyResp
	CanParticipateReq        = pb.CanParticipateReq
	CanParticipateResp       = pb.CanParticipateResp
	CanPublishReq            = pb.CanPublishReq
	CanPublishResp           = pb.CanPublishResp
	CancelStudentVerifyReq   = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp  = pb.CancelStudentVerifyResp
	CaptchaArgs              = pb.CaptchaArgs
	CheckCaptchaReq          = pb.CheckCaptchaReq
	CheckCaptchaResponse     = pb.CheckCaptchaResponse
	CheckQQEmailReq          = pb.CheckQQEmailReq
	CheckQQEmailResponse     = pb.CheckQQEmailResponse
	ConfirmStudentVerifyReq  = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp = pb.ConfirmStudentVerifyResp
	CreditLogItem            = pb.CreditLogItem
	DeleteFileReq            = pb.DeleteFileReq
	DeleteFileResponse       = pb.DeleteFileResponse
	DeleteUserReq            = pb.DeleteUserReq
	DeleteUserResponse       = pb.DeleteUserResponse
	ForgetPasswordReq        = pb.ForgetPasswordReq
	ForgetPasswordResponse   = pb.ForgetPasswordResponse
	GetAllTagsReq            = pb.GetAllTagsReq
	GetAllTagsResp           = pb.GetAllTagsResp
	GetCaptchaConfigReq      = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse = pb.GetCaptchaConfigResponse
	GetCreditInfoReq         = pb.GetCreditInfoReq
	GetCreditInfoResp        = pb.GetCreditInfoResp
	GetCreditLogsReq         = pb.GetCreditLogsReq
	GetCreditLogsResp        = pb.GetCreditLogsResp
	GetGroupUserReq          = pb.GetGroupUserReq
	GetGroupUserResponse     = pb.GetGroupUserResponse
	GetTagsByIdsReq          = pb.GetTagsByIdsReq
	GetTagsByIdsResp         = pb.GetTagsByIdsResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResponse      = pb.GetUserInfoResponse
	GetUserTagsReq           = pb.GetUserTagsReq
	GetUserTagsResponse      = pb.GetUserTagsResponse
	GetVerifyCurrentReq      = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp     = pb.GetVerifyCurrentResp
	GetVerifyInfoReq         = pb.GetVerifyInfoReq
	GetVerifyInfoResp        = pb.GetVerifyInfoResp
	GroupUserInfo            = pb.GroupUserInfo
	InitCreditReq            = pb.InitCreditReq
	InitCreditResp           = pb.InitCreditResp
	InterestTag              = pb.InterestTag
	IsVerifiedReq            = pb.IsVerifiedReq
	IsVerifiedResp           = pb.IsVerifiedResp
	LoginReq                 = pb.LoginReq
	LoginResponse            = pb.LoginResponse
	LoginUserInfo            = pb.LoginUserInfo
	LogoutReq                = pb.LogoutReq
	LogoutResponse           = pb.LogoutResponse
	RefreshReq               = pb.RefreshReq
	RefreshResponse          = pb.RefreshResponse
	RegisterReq              = pb.RegisterReq
	RegisterResponse         = pb.RegisterResponse
	SendQQEmailReq           = pb.SendQQEmailReq
	SendQQEmailResponse      = pb.SendQQEmailResponse
	TagBasicInfo             = pb.TagBasicInfo
	TagInfo                  = pb.TagInfo
	UpdatePasswordReq        = pb.UpdatePasswordReq
	UpdatePasswordResponse   = pb.UpdatePasswordResponse
	UpdateScoreReq           = pb.UpdateScoreReq
	UpdateScoreResp          = pb.UpdateScoreResp
	UpdateUserInfoReq        = pb.UpdateUserInfoReq
	UpdateUserInfoResponse   = pb.UpdateUserInfoResponse
	UpdateUserTagReq         = pb.UpdateUserTagReq
	UpdateUserTagResponse    = pb.UpdateUserTagResponse
	UpdateVerifyStatusReq    = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp   = pb.UpdateVerifyStatusResp
	UploadFileReq            = pb.UploadFileReq
	UploadFileResponse       = pb.UploadFileResponse
	UserInfo                 = pb.UserInfo
	UserTag                  = pb.UserTag
	VerifyModifiedData       = pb.VerifyModifiedData
	VerifyOcrData            = pb.VerifyOcrData

	UploadToQiNiu interface {
		UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResponse, error)
		DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResponse, error)
	}

	defaultUploadToQiNiu struct {
		cli zrpc.Client
	}
)

func NewUploadToQiNiu(cli zrpc.Client) UploadToQiNiu {
	return &defaultUploadToQiNiu{
		cli: cli,
	}
}

func (m *defaultUploadToQiNiu) UploadFile(ctx context.Context, in *UploadFileReq, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	client := pb.NewUploadToQiNiuClient(m.cli.Conn())
	return client.UploadFile(ctx, in, opts...)
}

func (m *defaultUploadToQiNiu) DeleteFile(ctx context.Context, in *DeleteFileReq, opts ...grpc.CallOption) (*DeleteFileResponse, error) {
	client := pb.NewUploadToQiNiuClient(m.cli.Conn())
	return client.DeleteFile(ctx, in, opts...)
}
