// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userbasicservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq    = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp   = pb.ApplyStudentVerifyResp
	CanParticipateReq        = pb.CanParticipateReq
	CanParticipateResp       = pb.CanParticipateResp
	CanPublishReq            = pb.CanPublishReq
	CanPublishResp           = pb.CanPublishResp
	CancelStudentVerifyReq   = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp  = pb.CancelStudentVerifyResp
	CaptchaArgs              = pb.CaptchaArgs
	CheckCaptchaReq          = pb.CheckCaptchaReq
	CheckCaptchaResponse     = pb.CheckCaptchaResponse
	CheckQQEmailReq          = pb.CheckQQEmailReq
	CheckQQEmailResponse     = pb.CheckQQEmailResponse
	ConfirmStudentVerifyReq  = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp = pb.ConfirmStudentVerifyResp
	CreditLogItem            = pb.CreditLogItem
	GetAllTagsReq            = pb.GetAllTagsReq
	GetAllTagsResp           = pb.GetAllTagsResp
	GetCaptchaConfigReq      = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse = pb.GetCaptchaConfigResponse
	GetCreditInfoReq         = pb.GetCreditInfoReq
	GetCreditInfoResp        = pb.GetCreditInfoResp
	GetCreditLogsReq         = pb.GetCreditLogsReq
	GetCreditLogsResp        = pb.GetCreditLogsResp
	GetGroupUserReq          = pb.GetGroupUserReq
	GetGroupUserResponse     = pb.GetGroupUserResponse
	GetTagsByIdsReq          = pb.GetTagsByIdsReq
	GetTagsByIdsResp         = pb.GetTagsByIdsResp
	GetUserInfoReq           = pb.GetUserInfoReq
	GetUserInfoResponse      = pb.GetUserInfoResponse
	GetUserTagsRep           = pb.GetUserTagsRep
	GetUserTagsResponse      = pb.GetUserTagsResponse
	GetVerifyCurrentReq      = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp     = pb.GetVerifyCurrentResp
	GetVerifyInfoReq         = pb.GetVerifyInfoReq
	GetVerifyInfoResp        = pb.GetVerifyInfoResp
	GroupUserInfo            = pb.GroupUserInfo
	InitCreditReq            = pb.InitCreditReq
	InitCreditResp           = pb.InitCreditResp
	InterestTag              = pb.InterestTag
	IsVerifiedReq            = pb.IsVerifiedReq
	IsVerifiedResp           = pb.IsVerifiedResp
	LoginReq                 = pb.LoginReq
	LoginResponse            = pb.LoginResponse
	LoginUserInfo            = pb.LoginUserInfo
	LogoutReq                = pb.LogoutReq
	LogoutResponse           = pb.LogoutResponse
	RefreshReq               = pb.RefreshReq
	RefreshResponse          = pb.RefreshResponse
	RegisterReq              = pb.RegisterReq
	RegisterResponse         = pb.RegisterResponse
	SendQQEmailReq           = pb.SendQQEmailReq
	SendQQEmailResponse      = pb.SendQQEmailResponse
	TagInfo                  = pb.TagInfo
	UpdateScoreReq           = pb.UpdateScoreReq
	UpdateScoreResp          = pb.UpdateScoreResp
	UpdateVerifyStatusReq    = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp   = pb.UpdateVerifyStatusResp
	UserInfo                 = pb.UserInfo
	VerifyModifiedData       = pb.VerifyModifiedData
	VerifyOcrData            = pb.VerifyOcrData

	UserBasicService interface {
		// 批量获取群聊用户的信息
		GetGroupUser(ctx context.Context, in *GetGroupUserReq, opts ...grpc.CallOption) (*GetGroupUserResponse, error)
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResponse, error)
		// 用户登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResponse, error)
		// 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 刷新短token
		RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*RefreshResponse, error)
		// 获取用户的信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	}

	defaultUserBasicService struct {
		cli zrpc.Client
	}
)

func NewUserBasicService(cli zrpc.Client) UserBasicService {
	return &defaultUserBasicService{
		cli: cli,
	}
}

// 批量获取群聊用户的信息
func (m *defaultUserBasicService) GetGroupUser(ctx context.Context, in *GetGroupUserReq, opts ...grpc.CallOption) (*GetGroupUserResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetGroupUser(ctx, in, opts...)
}

// 用户登录
func (m *defaultUserBasicService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 用户登出
func (m *defaultUserBasicService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 用户注册
func (m *defaultUserBasicService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 刷新短token
func (m *defaultUserBasicService) RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*RefreshResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 获取用户的信息
func (m *defaultUserBasicService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}
