// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userbasicservice

import (
	"context"

	"activity-platform/app/user/rpc/pb/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ApplyStudentVerifyReq       = pb.ApplyStudentVerifyReq
	ApplyStudentVerifyResp      = pb.ApplyStudentVerifyResp
	CanParticipateReq           = pb.CanParticipateReq
	CanParticipateResp          = pb.CanParticipateResp
	CanPublishReq               = pb.CanPublishReq
	CanPublishResp              = pb.CanPublishResp
	CancelStudentVerifyReq      = pb.CancelStudentVerifyReq
	CancelStudentVerifyResp     = pb.CancelStudentVerifyResp
	CaptchaArgs                 = pb.CaptchaArgs
	CheckCaptchaReq             = pb.CheckCaptchaReq
	CheckCaptchaResponse        = pb.CheckCaptchaResponse
	CheckQQEmailReq             = pb.CheckQQEmailReq
	CheckQQEmailResponse        = pb.CheckQQEmailResponse
	CheckUserExistsReq          = pb.CheckUserExistsReq
	CheckUserExistsResponse     = pb.CheckUserExistsResponse
	ConfirmStudentVerifyReq     = pb.ConfirmStudentVerifyReq
	ConfirmStudentVerifyResp    = pb.ConfirmStudentVerifyResp
	CreditLogItem               = pb.CreditLogItem
	DeleteUserReq               = pb.DeleteUserReq
	DeleteUserResponse          = pb.DeleteUserResponse
	ForgetPasswordReq           = pb.ForgetPasswordReq
	ForgetPasswordResponse      = pb.ForgetPasswordResponse
	GetAllInterestTagsReq       = pb.GetAllInterestTagsReq
	GetAllInterestTagsResp      = pb.GetAllInterestTagsResp
	GetAllTagsReq               = pb.GetAllTagsReq
	GetAllTagsResp              = pb.GetAllTagsResp
	GetCaptchaConfigReq         = pb.GetCaptchaConfigReq
	GetCaptchaConfigResponse    = pb.GetCaptchaConfigResponse
	GetCreditInfoReq            = pb.GetCreditInfoReq
	GetCreditInfoResp           = pb.GetCreditInfoResp
	GetCreditLogsReq            = pb.GetCreditLogsReq
	GetCreditLogsResp           = pb.GetCreditLogsResp
	GetGroupUserReq             = pb.GetGroupUserReq
	GetGroupUserResponse        = pb.GetGroupUserResponse
	GetSysImageReq              = pb.GetSysImageReq
	GetSysImageResp             = pb.GetSysImageResp
	GetTagsByIdsReq             = pb.GetTagsByIdsReq
	GetTagsByIdsResp            = pb.GetTagsByIdsResp
	GetUserHomeReq              = pb.GetUserHomeReq
	GetUserHomeResp             = pb.GetUserHomeResp
	GetUserInfoReq              = pb.GetUserInfoReq
	GetUserInfoResponse         = pb.GetUserInfoResponse
	GetUserTagsReq              = pb.GetUserTagsReq
	GetUserTagsResponse         = pb.GetUserTagsResponse
	GetVerifyCurrentReq         = pb.GetVerifyCurrentReq
	GetVerifyCurrentResp        = pb.GetVerifyCurrentResp
	GetVerifyInfoReq            = pb.GetVerifyInfoReq
	GetVerifyInfoResp           = pb.GetVerifyInfoResp
	GroupUserInfo               = pb.GroupUserInfo
	InitCreditReq               = pb.InitCreditReq
	InitCreditResp              = pb.InitCreditResp
	InterestTag                 = pb.InterestTag
	IsVerifiedReq               = pb.IsVerifiedReq
	IsVerifiedResp              = pb.IsVerifiedResp
	LoginReq                    = pb.LoginReq
	LoginResponse               = pb.LoginResponse
	LoginUserInfo               = pb.LoginUserInfo
	LogoutReq                   = pb.LogoutReq
	LogoutResponse              = pb.LogoutResponse
	ProcessOcrVerifyReq         = pb.ProcessOcrVerifyReq
	ProcessOcrVerifyResp        = pb.ProcessOcrVerifyResp
	RefreshReq                  = pb.RefreshReq
	RefreshResponse             = pb.RefreshResponse
	RegisterReq                 = pb.RegisterReq
	RegisterResponse            = pb.RegisterResponse
	SendQQEmailReq              = pb.SendQQEmailReq
	SendQQEmailResponse         = pb.SendQQEmailResponse
	TagBasicInfo                = pb.TagBasicInfo
	TagInfo                     = pb.TagInfo
	TagUsageCountReq            = pb.TagUsageCountReq
	TagUsageCountResp           = pb.TagUsageCountResp
	UpdatePasswordReq           = pb.UpdatePasswordReq
	UpdatePasswordResponse      = pb.UpdatePasswordResponse
	UpdateScoreReq              = pb.UpdateScoreReq
	UpdateScoreResp             = pb.UpdateScoreResp
	UpdateUserInfoReq           = pb.UpdateUserInfoReq
	UpdateUserInfoResponse      = pb.UpdateUserInfoResponse
	UpdateUserTagReq            = pb.UpdateUserTagReq
	UpdateUserTagResponse       = pb.UpdateUserTagResponse
	UpdateVerifyStatusReq       = pb.UpdateVerifyStatusReq
	UpdateVerifyStatusResp      = pb.UpdateVerifyStatusResp
	UploadActivityCoverReq      = pb.UploadActivityCoverReq
	UploadActivityCoverResp     = pb.UploadActivityCoverResp
	UploadAvatarReq             = pb.UploadAvatarReq
	UploadAvatarResp            = pb.UploadAvatarResp
	UploadStudentCardImagesReq  = pb.UploadStudentCardImagesReq
	UploadStudentCardImagesResp = pb.UploadStudentCardImagesResp
	UploadSysImageReq           = pb.UploadSysImageReq
	UploadSysImageResp          = pb.UploadSysImageResp
	UserHomeActivityItem        = pb.UserHomeActivityItem
	UserHomeActivityList        = pb.UserHomeActivityList
	UserHomeInfo                = pb.UserHomeInfo
	UserHomeTag                 = pb.UserHomeTag
	UserInfo                    = pb.UserInfo
	UserTag                     = pb.UserTag
	VerifyModifiedData          = pb.VerifyModifiedData
	VerifyOcrData               = pb.VerifyOcrData

	UserBasicService interface {
		// 批量获取群聊用户的信息
		GetGroupUser(ctx context.Context, in *GetGroupUserReq, opts ...grpc.CallOption) (*GetGroupUserResponse, error)
		// 用户登录
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResponse, error)
		// 用户登出
		Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResponse, error)
		// 用户注册
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResponse, error)
		// 刷新短token
		RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*RefreshResponse, error)
		// 获取用户的信息
		GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
		// 修改用户密码
		UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResponse, error)
		// 修改用户信息
		UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error)
		// 用户注销自己
		DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResponse, error)
		// 用户忘记密码
		ForgetPassword(ctx context.Context, in *ForgetPasswordReq, opts ...grpc.CallOption) (*ForgetPasswordResponse, error)
		// 检查用户是否存在（通过邮箱）
		CheckUserExists(ctx context.Context, in *CheckUserExistsReq, opts ...grpc.CallOption) (*CheckUserExistsResponse, error)
		// 获取用户主页信息
		GetUserHome(ctx context.Context, in *GetUserHomeReq, opts ...grpc.CallOption) (*GetUserHomeResp, error)
		// 获取系统图片
		GetSysImage(ctx context.Context, in *GetSysImageReq, opts ...grpc.CallOption) (*GetSysImageResp, error)
	}

	defaultUserBasicService struct {
		cli zrpc.Client
	}
)

func NewUserBasicService(cli zrpc.Client) UserBasicService {
	return &defaultUserBasicService{
		cli: cli,
	}
}

// 批量获取群聊用户的信息
func (m *defaultUserBasicService) GetGroupUser(ctx context.Context, in *GetGroupUserReq, opts ...grpc.CallOption) (*GetGroupUserResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetGroupUser(ctx, in, opts...)
}

// 用户登录
func (m *defaultUserBasicService) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

// 用户登出
func (m *defaultUserBasicService) Logout(ctx context.Context, in *LogoutReq, opts ...grpc.CallOption) (*LogoutResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Logout(ctx, in, opts...)
}

// 用户注册
func (m *defaultUserBasicService) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

// 刷新短token
func (m *defaultUserBasicService) RefreshToken(ctx context.Context, in *RefreshReq, opts ...grpc.CallOption) (*RefreshResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.RefreshToken(ctx, in, opts...)
}

// 获取用户的信息
func (m *defaultUserBasicService) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetUserInfo(ctx, in, opts...)
}

// 修改用户密码
func (m *defaultUserBasicService) UpdatePassword(ctx context.Context, in *UpdatePasswordReq, opts ...grpc.CallOption) (*UpdatePasswordResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.UpdatePassword(ctx, in, opts...)
}

// 修改用户信息
func (m *defaultUserBasicService) UpdateUserInfo(ctx context.Context, in *UpdateUserInfoReq, opts ...grpc.CallOption) (*UpdateUserInfoResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.UpdateUserInfo(ctx, in, opts...)
}

// 用户注销自己
func (m *defaultUserBasicService) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.DeleteUser(ctx, in, opts...)
}

// 用户忘记密码
func (m *defaultUserBasicService) ForgetPassword(ctx context.Context, in *ForgetPasswordReq, opts ...grpc.CallOption) (*ForgetPasswordResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.ForgetPassword(ctx, in, opts...)
}

// 检查用户是否存在（通过邮箱）
func (m *defaultUserBasicService) CheckUserExists(ctx context.Context, in *CheckUserExistsReq, opts ...grpc.CallOption) (*CheckUserExistsResponse, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.CheckUserExists(ctx, in, opts...)
}

// 获取用户主页信息
func (m *defaultUserBasicService) GetUserHome(ctx context.Context, in *GetUserHomeReq, opts ...grpc.CallOption) (*GetUserHomeResp, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetUserHome(ctx, in, opts...)
}

// 获取系统图片
func (m *defaultUserBasicService) GetSysImage(ctx context.Context, in *GetSysImageReq, opts ...grpc.CallOption) (*GetSysImageResp, error) {
	client := pb.NewUserBasicServiceClient(m.cli.Conn())
	return client.GetSysImage(ctx, in, opts...)
}
