// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: activity.proto

package server

import (
	"context"

	"activity-platform/app/activity/rpc/activity"
	"activity-platform/app/activity/rpc/internal/logic/activityservice"
	"activity-platform/app/activity/rpc/internal/svc"
)

type ActivityServiceServer struct {
	svcCtx *svc.ServiceContext
	activity.UnimplementedActivityServiceServer
}

func NewActivityServiceServer(svcCtx *svc.ServiceContext) *ActivityServiceServer {
	return &ActivityServiceServer{
		svcCtx: svcCtx,
	}
}

// RegisterActivity 报名活动
func (s *ActivityServiceServer) RegisterActivity(ctx context.Context, in *activity.RegisterActivityRequest) (*activity.RegisterActivityResponse, error) {
	l := activityservicelogic.NewRegisterActivityLogic(ctx, s.svcCtx)
	return l.RegisterActivity(in)
}

// CancelActivities 取消报名活动
func (s *ActivityServiceServer) CancelActivities(ctx context.Context, in *activity.CancelActivityRequest) (*activity.CancelActivityResponse, error) {
	l := activityservicelogic.NewCancelActivitiesLogic(ctx, s.svcCtx)
	return l.CancelActivities(in)
}

// GetActivityList 获取待参加/已参加活动信息列表
func (s *ActivityServiceServer) GetActivityList(ctx context.Context, in *activity.GetActivityListRequest) (*activity.GetActivityListResponse, error) {
	l := activityservicelogic.NewGetActivityListLogic(ctx, s.svcCtx)
	return l.GetActivityList(in)
}

// VerifyTicket 核销票券
func (s *ActivityServiceServer) VerifyTicket(ctx context.Context, in *activity.VerifyTicketRequest) (*activity.VerifyTicketResponse, error) {
	l := activityservicelogic.NewVerifyTicketLogic(ctx, s.svcCtx)
	return l.VerifyTicket(in)
}

// GetTicketList 获取个人票券列表
func (s *ActivityServiceServer) GetTicketList(ctx context.Context, in *activity.GetTicketListRequest) (*activity.GetTicketListResponse, error) {
	l := activityservicelogic.NewGetTicketListLogic(ctx, s.svcCtx)
	return l.GetTicketList(in)
}

// GetTicketDetail 获取票券详情
func (s *ActivityServiceServer) GetTicketDetail(ctx context.Context, in *activity.GetTicketDetailRequest) (*activity.GetTicketDetailResponse, error) {
	l := activityservicelogic.NewGetTicketDetailLogic(ctx, s.svcCtx)
	return l.GetTicketDetail(in)
}

// GetRegisteredCount 获取报名数量
func (s *ActivityServiceServer) GetRegisteredCount(ctx context.Context, in *activity.GetRegisteredCountRequest) (*activity.GetRegisteredCountResponse, error) {
	l := activityservicelogic.NewGetRegisteredCountLogic(ctx, s.svcCtx)
	return l.GetRegisteredCount(in)
}

// ==================== CRUD 接口 ====================
func (s *ActivityServiceServer) CreateActivity(ctx context.Context, in *activity.CreateActivityReq) (*activity.CreateActivityResp, error) {
	l := activityservicelogic.NewCreateActivityLogic(ctx, s.svcCtx)
	return l.CreateActivity(in)
}

func (s *ActivityServiceServer) UpdateActivity(ctx context.Context, in *activity.UpdateActivityReq) (*activity.UpdateActivityResp, error) {
	l := activityservicelogic.NewUpdateActivityLogic(ctx, s.svcCtx)
	return l.UpdateActivity(in)
}

func (s *ActivityServiceServer) DeleteActivity(ctx context.Context, in *activity.DeleteActivityReq) (*activity.DeleteActivityResp, error) {
	l := activityservicelogic.NewDeleteActivityLogic(ctx, s.svcCtx)
	return l.DeleteActivity(in)
}

func (s *ActivityServiceServer) GetActivity(ctx context.Context, in *activity.GetActivityReq) (*activity.GetActivityResp, error) {
	l := activityservicelogic.NewGetActivityLogic(ctx, s.svcCtx)
	return l.GetActivity(in)
}

func (s *ActivityServiceServer) ListActivities(ctx context.Context, in *activity.ListActivitiesReq) (*activity.ListActivitiesResp, error) {
	l := activityservicelogic.NewListActivitiesLogic(ctx, s.svcCtx)
	return l.ListActivities(in)
}

// ==================== 状态操作接口 ====================
func (s *ActivityServiceServer) SubmitActivity(ctx context.Context, in *activity.SubmitActivityReq) (*activity.SubmitActivityResp, error) {
	l := activityservicelogic.NewSubmitActivityLogic(ctx, s.svcCtx)
	return l.SubmitActivity(in)
}

func (s *ActivityServiceServer) ApproveActivity(ctx context.Context, in *activity.ApproveActivityReq) (*activity.ApproveActivityResp, error) {
	l := activityservicelogic.NewApproveActivityLogic(ctx, s.svcCtx)
	return l.ApproveActivity(in)
}

func (s *ActivityServiceServer) RejectActivity(ctx context.Context, in *activity.RejectActivityReq) (*activity.RejectActivityResp, error) {
	l := activityservicelogic.NewRejectActivityLogic(ctx, s.svcCtx)
	return l.RejectActivity(in)
}

func (s *ActivityServiceServer) CancelActivity(ctx context.Context, in *activity.CancelActivityReq) (*activity.CancelActivityResp, error) {
	l := activityservicelogic.NewCancelActivityLogic(ctx, s.svcCtx)
	return l.CancelActivity(in)
}

// ==================== 搜索接口 ====================
func (s *ActivityServiceServer) SearchActivities(ctx context.Context, in *activity.SearchActivitiesReq) (*activity.SearchActivitiesResp, error) {
	l := activityservicelogic.NewSearchActivitiesLogic(ctx, s.svcCtx)
	return l.SearchActivities(in)
}

func (s *ActivityServiceServer) GetHotActivities(ctx context.Context, in *activity.GetHotActivitiesReq) (*activity.GetHotActivitiesResp, error) {
	l := activityservicelogic.NewGetHotActivitiesLogic(ctx, s.svcCtx)
	return l.GetHotActivities(in)
}

// ==================== 分类标签接口 ====================
func (s *ActivityServiceServer) ListCategories(ctx context.Context, in *activity.ListCategoriesReq) (*activity.ListCategoriesResp, error) {
	l := activityservicelogic.NewListCategoriesLogic(ctx, s.svcCtx)
	return l.ListCategories(in)
}

func (s *ActivityServiceServer) ListTags(ctx context.Context, in *activity.ListTagsReq) (*activity.ListTagsResp, error) {
	l := activityservicelogic.NewListTagsLogic(ctx, s.svcCtx)
	return l.ListTags(in)
}

// ==================== 浏览量接口 ====================
func (s *ActivityServiceServer) IncrViewCount(ctx context.Context, in *activity.IncrViewCountReq) (*activity.IncrViewCountResp, error) {
	l := activityservicelogic.NewIncrViewCountLogic(ctx, s.svcCtx)
	return l.IncrViewCount(in)
}

// ==================== 内部接口（供其他微服务调用）====================
func (s *ActivityServiceServer) GetActivityBasic(ctx context.Context, in *activity.GetActivityBasicReq) (*activity.GetActivityBasicResp, error) {
	l := activityservicelogic.NewGetActivityBasicLogic(ctx, s.svcCtx)
	return l.GetActivityBasic(in)
}

// 批量获取活动基本信息
func (s *ActivityServiceServer) BatchGetActivityBasic(ctx context.Context, in *activity.BatchGetActivityBasicReq) (*activity.BatchGetActivityBasicResp, error) {
	l := activityservicelogic.NewBatchGetActivityBasicLogic(ctx, s.svcCtx)
	return l.BatchGetActivityBasic(in)
}

// 获取用户已发布的活动列表（User 服务调用，用于展示用户主页）
func (s *ActivityServiceServer) GetUserPublishedActivities(ctx context.Context, in *activity.GetUserPublishedActivitiesReq) (*activity.GetUserPublishedActivitiesResp, error) {
	l := activityservicelogic.NewGetUserPublishedActivitiesLogic(ctx, s.svcCtx)
	return l.GetUserPublishedActivities(in)
}
